In [1]:
import os
from nwtrace import *
import pandas as pd
import geopandas as gpd

from pathlib import Path

In [2]:
lines = Path('data/more/full_sewers.geojson')
nodes = Path('data/more/all_node_connections.geojson')

lines_gdf = gpd.read_file(lines)
nodes_gdf = gpd.read_file(nodes)

In [3]:
multiple = True
upstream_only = False
downstream_only = False
verbose = True

sewer_id_field = 'FACILITYID'
upstream_field = 'FROMMH'
downstream_field = 'TOMH'

outfall_file = 'data/more/BC_outfalls.csv'
id_field = 'Asset Identification'

outfalls = pd.read_csv(outfall_file)[id_field].tolist()

target_endpoints = outfalls

outputname_extra = "allBC_"
output_dir = f"./out"
if not os.path.exists(output_dir):
    os.mkdir(output_dir)

result = []

sewershed = NWTrace(
    network=lines_gdf,
    id_field=sewer_id_field,
    upstream_field = upstream_field,
    downstream_field = downstream_field,
    verbose=verbose,
    output_dir=output_dir,
)

# additional connections
fittings = gpd.read_file("data/more/fitting_connections.geojson")
nodes_up = (fittings[["FACILITYID", "TO_FIXED"]]
            .dropna(subset=["FACILITYID", "TO_FIXED"]) # remove rows with None values
            .rename(columns={"FACILITYID": 'node_id', "TO_FIXED": 'segment_id'})
            .to_dict(orient="records"))

sewershed.add_upstream_nodes(nodes_up)


node_lookup, seg_lookup = sewershed.get_lookup_tables()

Added 5245 node-segment connection(s)
Created 627 new node(s)
Created 374 new segment(s).

In [10]:
errors = utils.verify_network_geometry(
    lines=lines_gdf,
    points=nodes_gdf,
    lookup_table=seg_lookup,
    line_id_field="FACILITYID",
    point_id_field="FACILITYID",
    threshold=100
)

100%|██████████| 169323/169323 [00:01<00:00, 103710.16it/s]

1176 Errors Found
Average Distance 0.14510461119443013 units

In [5]:
err_df = gpd.GeoDataFrame.from_dict(errors, geometry="geometry")
err_df = err_df.set_crs(lines_gdf.crs)

err_df.to_file("out/errors.gpkg", driver="GPKG", layer="errorsv1")

err_df

,node_id,segment_id,error_t,error_msg,dist,geometry
0,MH5212822131,SL0000-001-5481,missing node,node MH5212822131 does not exist in dataset,-1.000000,"MULTILINESTRING ((322146.483 4852349.718, 3221..."
1,MH4856521416,SL0000-012-0241,spatial,node MH4856521416 is more than 10 units from s...,53.931959,"MULTILINESTRING ((321483.472 4848889.549, 3214..."
2,MH5151728331,SL0000-017-3071,missing node,node MH5151728331 does not exist in dataset,-1.000000,"MULTILINESTRING ((328347.352 4851739.48, 32833..."
3,MH5194926776,SL0000-027-4231,missing node,node MH5194926776 does not exist in dataset,-1.000000,"MULTILINESTRING ((326791.821 4852171.698, 3267..."
4,MH5008926783,SL0000-027-9001,missing node,node MH5008926783 does not exist in dataset,-1.000000,"MULTILINESTRING ((326799.977 4850308.313, 3267..."
...,...,...,...,...,...,...
1220,None,SL4000-007,missing segment,segment SL4000-007 does not exist in dataset,-1.000000,None
1221,None,SL110491,missing segment,segment SL110491 does not exist in dataset,-1.000000,None
1222,None,SL1404719,missing segment,segment SL1404719 does not exist in dataset,-1.000000,None
1223,None,SL2000-011,missing segment,segment SL2000-011 does not exist in dataset,-1.000000,None
1224,None,SL4163521,missing segment,segment SL4163521 does not exist in dataset,-1.000000,None

In [6]:
cons_err_df = err_df.groupby(["error_t"]).count()
cons_err_df

                 node_id  segment_id  error_msg  dist  geometry
error_t
missing node         789         789        789   789       789
missing segment        0         374        374   374         0
spatial               62          62         62    62        62

In [9]:
ids_dup = utils.count_duplicates(lines_gdf, "FACILITYID", minimum_count=0)
ids_dup

{'duplicate_count': {'SL0000-000-0091': 1,
  'SL0000-000-0181': 1,
  'SL0000-000-0271': 1,
  'SL0000-000-0361': 1,
  'SL0000-000-0451': 1,
  'SL0000-000-0541': 1,
  'SL0000-000-0631': 1,
  'SL0000-000-0721': 1,
  'SL0000-000-0722': 1,
  'SL0000-000-0811': 1,
  'SL0000-000-0901': 1,
  'SL0000-000-0991': 1,
  'SL0000-000-1081': 1,
  'SL0000-000-1171': 1,
  'SL0000-000-1261': 1,
  'SL0000-000-1351': 1,
  'SL0000-000-1441': 1,
  'SL0000-000-1531': 1,
  'SL0000-000-1621': 1,
  'SL0000-000-1711': 1,
  'SL0000-000-1801': 1,
  'SL0000-000-1891': 1,
  'SL0000-000-1981': 1,
  'SL0000-000-2071': 1,
  'SL0000-000-2161': 1,
  'SL0000-000-3961': 1,
  'SL0000-000-4051': 1,
  'SL0000-000-4141': 1,
  'SL0000-000-4231': 1,
  'SL0000-000-4232': 1,
  'SL0000-000-4321': 1,
  'SL0000-000-4411': 1,
  'SL0000-000-4501': 1,
  'SL0000-000-4591': 1,
  'SL0000-000-4681': 1,
  'SL0000-000-4771': 1,
  'SL0000-000-4861': 1,
  'SL0000-000-4951': 1,
  'SL0000-000-5041': 1,
  'SL0000-000-5131': 1,
  'SL0000-000-5221': 1,
  'SL0000-000-5311': 1,
  'SL0000-000-5401': 1,
  'SL0000-000-5491': 1,
  'SL0000-000-5671': 1,
  'SL0000-000-5761': 1,
  'SL0000-000-5851': 1,
  'SL0000-000-5941': 1,
  'SL0000-000-6031': 1,
  'SL0000-000-6121': 1,
  'SL0000-000-6211': 1,
  'SL0000-000-6301': 1,
  'SL0000-000-6391': 1,
  'SL0000-000-6571': 1,
  'SL0000-000-8371': 1,
  'SL0000-000-8461': 1,
  'SL0000-000-8551': 1,
  'SL0000-000-8641': 1,
  'SL0000-000-8731': 1,
  'SL0000-000-8732': 1,
  'SL0000-000-8821': 1,
  'SL0000-000-8911': 1,
  'SL0000-000-9001': 1,
  'SL0000-000-9091': 1,
  'SL0000-000-9181': 1,
  'SL0000-000-9271': 1,
  'SL0000-000-9361': 1,
  'SL0000-000-9451': 1,
  'SL0000-000-9541': 1,
  'SL0000-001-0531': 1,
  'SL0000-001-0621': 1,
  'SL0000-001-0711': 1,
  'SL0000-001-0801': 1,
  'SL0000-001-0891': 1,
  'SL0000-001-0981': 1,
  'SL0000-001-1071': 1,
  'SL0000-001-1161': 1,
  'SL0000-001-1251': 1,
  'SL0000-001-1341': 1,
  'SL0000-001-1431': 1,
  'SL0000-001-1521': 1,
  'SL0000-001-1522': 1,
  'SL0000-001-1611': 1,
  'SL0000-001-1612': 1,
  'SL0000-001-1701': 1,
  'SL0000-001-1702': 1,
  'SL0000-001-1791': 1,
  'SL0000-001-1792': 1,
  'SL0000-001-1881': 1,
  'SL0000-001-1882': 1,
  'SL0000-001-1971': 1,
  'SL0000-001-1972': 1,
  'SL0000-001-2061': 1,
  'SL0000-001-2062': 1,
  'SL0000-001-2151': 1,
  'SL0000-001-2152': 1,
  'SL0000-001-2241': 1,
  'SL0000-001-2331': 1,
  'SL0000-001-4491': 1,
  'SL0000-001-4581': 1,
  'SL0000-001-4671': 1,
  'SL0000-001-4761': 1,
  'SL0000-001-4851': 1,
  'SL0000-001-5301': 1,
  'SL0000-001-5391': 1,
  'SL0000-001-5481': 1,
  'SL0000-001-5571': 1,
  'SL0000-001-5661': 1,
  'SL0000-001-5751': 1,
  'SL0000-001-5841': 1,
  'SL0000-001-5931': 1,
  'SL0000-001-6021': 1,
  'SL0000-001-6111': 1,
  'SL0000-001-6201': 1,
  'SL0000-001-6291': 1,
  'SL0000-001-6381': 1,
  'SL0000-001-6471': 1,
  'SL0000-001-6561': 1,
  'SL0000-001-6651': 1,
  'SL0000-001-6741': 1,
  'SL0000-001-6831': 1,
  'SL0000-001-6921': 1,
  'SL0000-001-8721': 1,
  'SL0000-001-8811': 1,
  'SL0000-001-8901': 1,
  'SL0000-001-8902': 1,
  'SL0000-001-8991': 1,
  'SL0000-001-9081': 1,
  'SL0000-001-9171': 1,
  'SL0000-001-9261': 1,
  'SL0000-001-9351': 1,
  'SL0000-001-9441': 1,
  'SL0000-001-9442': 1,
  'SL0000-001-9531': 1,
  'SL0000-001-9532': 1,
  'SL0000-001-9621': 1,
  'SL0000-001-9711': 1,
  'SL0000-001-9801': 1,
  'SL0000-001-9891': 1,
  'SL0000-002-1511': 1,
  'SL0000-002-1601': 1,
  'SL0000-002-1602': 1,
  'SL0000-002-1691': 1,
  'SL0000-002-1781': 1,
  'SL0000-002-1871': 1,
  'SL0000-002-1961': 1,
  'SL0000-002-2051': 1,
  'SL0000-002-2141': 1,
  'SL0000-002-2231': 1,
  'SL0000-002-2321': 1,
  'SL0000-002-2411': 1,
  'SL0000-002-2501': 1,
  'SL0000-002-2591': 1,
  'SL0000-002-2681': 1,
  'SL0000-002-2771': 1,
  'SL0000-002-2861': 1,
  'SL0000-002-2951': 1,
  'SL0000-002-3041': 1,
  'SL0000-002-3131': 1,
  'SL0000-002-3221': 1,
  'SL0000-002-4661': 1,
  'SL0000-002-4751': 1,
  'SL0000-002-4841': 1,
  'SL0000-002-4931': 1,
  'SL0000-002-5021': 1,
  'SL0000-002-5111': 1,
  'SL0000-002-5201': 1,
  'SL0000-002-5291': 1,
  'SL0000-002-5291-1': 1,
  'SL0000-002-5381': 1,
  'SL0000-002-5471': 1,
  'SL0000-002-5651': 1,
  'SL0000-002-5741': 1,
  'SL0000-002-5831': 1,
  'SL0000-002-5921': 1,
  'SL0000-002-6011': 1,
  'SL0000-002-6101': 1,
  'SL0000-002-6191': 1,
  'SL0000-002-6281': 1,
  'SL0000-002-6371': 1,
  'SL0000-002-7991': 1,
  'SL0000-002-8531': 1,
  'SL0000-002-8621': 1,
  'SL0000-002-8711': 1,
  'SL0000-002-8801': 1,
  'SL0000-002-8891': 1,
  'SL0000-002-8981': 1,
  'SL0000-002-9071': 1,
  'SL0000-002-9161': 1,
  'SL0000-002-9251': 1,
  'SL0000-002-9341': 1,
  'SL0000-002-9431': 1,
  'SL0000-002-9521': 1,
  'SL0000-002-9611': 1,
  'SL0000-002-9701': 1,
  'SL0000-002-9791': 1,
  'SL0000-002-9881': 1,
  'SL0000-002-9971': 1,
  'SL0000-003-0061': 1,
  'SL0000-003-0151': 1,
  'SL0000-003-0241': 1,
  'SL0000-003-0331': 1,
  'SL0000-003-0421': 1,
  'SL0000-003-0511': 1,
  'SL0000-003-0601': 1,
  'SL0000-003-0691': 1,
  'SL0000-003-0781': 1,
  'SL0000-003-0871': 1,
  'SL0000-003-0961': 1,
  'SL0000-003-1051': 1,
  'SL0000-003-1141': 1,
  'SL0000-003-1231': 1,
  'SL0000-003-1321': 1,
  'SL0000-003-1411': 1,
  'SL0000-003-1501': 1,
  'SL0000-003-1591': 1,
  'SL0000-003-1681': 1,
  'SL0000-003-1771': 1,
  'SL0000-003-1861': 1,
  'SL0000-003-1951': 1,
  'SL0000-003-2041': 1,
  'SL0000-003-2131': 1,
  'SL0000-003-4831': 1,
  'SL0000-003-4921': 1,
  'SL0000-003-5011': 1,
  'SL0000-003-5101': 1,
  'SL0000-003-5191': 1,
  'SL0000-003-5281': 1,
  'SL0000-003-5371': 1,
  'SL0000-003-5461': 1,
  'SL0000-003-5551': 1,
  'SL0000-003-5641': 1,
  'SL0000-003-5731': 1,
  'SL0000-003-5821': 1,
  'SL0000-003-5911': 1,
  'SL0000-003-6001': 1,
  'SL0000-003-6091': 1,
  'SL0000-003-6181': 1,
  'SL0000-003-6271': 1,
  'SL0000-003-6361': 1,
  'SL0000-003-6451': 1,
  'SL0000-003-6541': 1,
  'SL0000-003-6631': 1,
  'SL0000-003-6721': 1,
  'SL0000-003-6811': 1,
  'SL0000-003-6901': 1,
  'SL0000-003-6991': 1,
  'SL0000-003-7081': 1,
  'SL0000-003-7171': 1,
  'SL0000-003-7261': 1,
  'SL0000-003-9151': 1,
  'SL0000-003-9241': 1,
  'SL0000-003-9331': 1,
  'SL0000-003-9421': 1,
  'SL0000-003-9511': 1,
  'SL0000-003-9601': 1,
  'SL0000-003-9691': 1,
  'SL0000-003-9781': 1,
  'SL0000-003-9871': 1,
  'SL0000-003-9961': 1,
  'SL0000-004-0051': 1,
  'SL0000-004-0141': 1,
  'SL0000-004-0231': 1,
  'SL0000-004-0321': 1,
  'SL0000-004-0411': 1,
  'SL0000-004-0501': 1,
  'SL0000-004-0591': 1,
  'SL0000-004-0681': 1,
  'SL0000-004-0771': 1,
  'SL0000-004-0951': 1,
  'SL0000-004-1041': 1,
  'SL0000-004-1131': 1,
  'SL0000-004-1221': 1,
  'SL0000-004-1311': 1,
  'SL0000-004-2931': 1,
  'SL0000-004-3021': 1,
  'SL0000-004-3111': 1,
  'SL0000-004-3201': 1,
  'SL0000-004-3291': 1,
  'SL0000-004-3381': 1,
  'SL0000-004-3471': 1,
  'SL0000-004-3561': 1,
  'SL0000-004-3651': 1,
  'SL0000-004-3741': 1,
  'SL0000-004-3831': 1,
  'SL0000-004-3921': 1,
  'SL0000-004-4011': 1,
  'SL0000-004-4101': 1,
  'SL0000-004-4191': 1,
  'SL0000-004-4281': 1,
  'SL0000-004-4371': 1,
  'SL0000-004-4461': 1,
  'SL0000-004-4551': 1,
  'SL0000-004-4641': 1,
  'SL0000-004-4731': 1,
  'SL0000-004-4821': 1,
  'SL0000-004-4911': 1,
  'SL0000-004-5001': 1,
  'SL0000-004-5091': 1,
  'SL0000-004-5181': 1,
  'SL0000-004-5271': 1,
  'SL0000-004-6531': 1,
  'SL0000-004-6621': 1,
  'SL0000-004-6711': 1,
  'SL0000-004-6801': 1,
  'SL0000-004-6891': 1,
  'SL0000-004-6981': 1,
  'SL0000-004-7071': 1,
  'SL0000-004-7161': 1,
  'SL0000-004-7251': 1,
  'SL0000-004-7341': 1,
  'SL0000-004-7431': 1,
  'SL0000-004-7521': 1,
  'SL0000-004-7611': 1,
  'SL0000-004-7701': 1,
  'SL0000-004-7791': 1,
  'SL0000-004-7881': 1,
  'SL0000-004-7971': 1,
  'SL0000-004-8061': 1,
  'SL0000-004-8151': 1,
  'SL0000-004-8241': 1,
  'SL0000-004-8331': 1,
  'SL0000-004-8421': 1,
  'SL0000-004-8511': 1,
  'SL0000-004-8601': 1,
  'SL0000-004-8691': 1,
  'SL0000-004-8781': 1,
  'SL0000-004-8871': 1,
  'SL0000-005-0221': 1,
  'SL0000-005-0311': 1,
  'SL0000-005-0401': 1,
  'SL0000-005-0491': 1,
  'SL0000-005-0581': 1,
  'SL0000-005-0671': 1,
  'SL0000-005-0761': 1,
  'SL0000-005-0851': 1,
  'SL0000-005-0941': 1,
  'SL0000-005-0942': 1,
  'SL0000-005-1031': 1,
  'SL0000-005-1121': 1,
  'SL0000-005-1211': 1,
  'SL0000-005-1301': 1,
  'SL0000-005-1391': 1,
  'SL0000-005-1481': 1,
  'SL0000-005-1571': 1,
  'SL0000-005-1661': 1,
  'SL0000-005-1751': 1,
  'SL0000-005-1841': 1,
  'SL0000-005-1931': 1,
  'SL0000-005-1932': 1,
  'SL0000-005-3191': 1,
  'SL0000-005-3461': 1,
  'SL0000-005-3462': 1,
  'SL0000-005-3551': 1,
  'SL0000-005-3641': 1,
  'SL0000-005-3731': 1,
  'SL0000-005-3821': 1,
  'SL0000-005-3822': 1,
  'SL0000-005-3911': 1,
  'SL0000-005-4091': 1,
  'SL0000-005-4181': 1,
  'SL0000-005-4271': 1,
  'SL0000-005-4361': 1,
  'SL0000-005-4362': 1,
  'SL0000-005-4451': 1,
  'SL0000-005-4541': 1,
  'SL0000-005-4631': 1,
  'SL0000-005-4721': 1,
  'SL0000-005-4722': 1,
  'SL0000-005-4811': 1,
  'SL0000-005-4901': 1,
  'SL0000-005-4991': 1,
  'SL0000-005-5081': 1,
  'SL0000-005-5171': 1,
  'SL0000-005-5261': 1,
  'SL0000-005-6791': 1,
  'SL0000-005-7691': 1,
  'SL0000-005-7781': 1,
  'SL0000-005-7871': 1,
  'SL0000-005-7961': 1,
  'SL0000-005-8411': 1,
  'SL0000-005-8501': 1,
  'SL0000-005-8591': 1,
  'SL0000-005-8681': 1,
  'SL0000-005-8771': 1,
  'SL0000-005-8861': 1,
  'SL0000-005-8951': 1,
  'SL0000-005-9041': 1,
  'SL0000-005-9131': 1,
  'SL0000-005-9221': 1,
  'SL0000-005-9311': 1,
  'SL0000-005-9401': 1,
  'SL0000-005-9491': 1,
  'SL0000-005-9581': 1,
  'SL0000-005-9671': 1,
  'SL0000-005-9761': 1,
  'SL0000-005-9851': 1,
  'SL0000-005-9941': 1,
  'SL0000-006-0031': 1,
  'SL0000-006-0121': 1,
  'SL0000-006-0211': 1,
  'SL0000-006-0301': 1,
  'SL0000-006-0391': 1,
  'SL0000-006-0481': 1,
  'SL0000-006-0571': 1,
  'SL0000-006-0661': 1,
  'SL0000-006-0751': 1,
  'SL0000-006-0841': 1,
  'SL0000-006-0931': 1,
  'SL0000-006-2821': 1,
  'SL0000-006-2911': 1,
  'SL0000-006-3001': 1,
  'SL0000-006-3091': 1,
  'SL0000-006-3181': 1,
  'SL0000-006-3271': 1,
  'SL0000-006-3272': 1,
  'SL0000-006-3361': 1,
  'SL0000-006-3451': 1,
  'SL0000-006-3541': 1,
  'SL0000-006-3631': 1,
  'SL0000-006-3721': 1,
  'SL0000-006-3811': 1,
  'SL0000-006-3901': 1,
  'SL0000-006-3991': 1,
  'SL0000-006-4081': 1,
  'SL0000-006-4171': 1,
  'SL0000-006-4261': 1,
  'SL0000-006-4262': 1,
  'SL0000-006-4351': 1,
  'SL0000-006-4441': 1,
  'SL0000-006-4531': 1,
  'SL0000-006-4621': 1,
  'SL0000-006-4711': 1,
  'SL0000-006-4801': 1,
  'SL0000-006-6691': 1,
  'SL0000-006-6871': 1,
  'SL0000-006-6961': 1,
  'SL0000-006-7051': 1,
  'SL0000-006-7141': 1,
  'SL0000-006-7231': 1,
  'SL0000-006-7321': 1,
  'SL0000-006-7411': 1,
  'SL0000-006-7501': 1,
  'SL0000-006-8491': 1,
  'SL0000-006-8581': 1,
  'SL0000-006-8671': 1,
  'SL0000-006-8761': 1,
  'SL0000-006-8851': 1,
  'SL0000-006-8941': 1,
  'SL0000-006-9031': 1,
  'SL0000-006-9121': 1,
  'SL0000-006-9301': 1,
  'SL0000-006-9391': 1,
  'SL0000-006-9481': 1,
  'SL0000-006-9571': 1,
  'SL0000-006-9661': 1,
  'SL0000-006-9751': 1,
  'SL0000-006-9841': 1,
  'SL0000-007-1101': 1,
  'SL0000-007-1371': 1,
  'SL0000-007-1551': 1,
  'SL0000-007-1641': 1,
  'SL0000-007-1731': 1,
  'SL0000-007-1821': 1,
  'SL0000-007-1911': 1,
  'SL0000-007-2001': 1,
  'SL0000-007-2091': 1,
  'SL0000-007-2271': 1,
  'SL0000-007-2901': 1,
  'SL0000-007-3261': 1,
  'SL0000-007-3351': 1,
  'SL0000-007-3441': 1,
  'SL0000-007-3531': 1,
  'SL0000-007-3711': 1,
  'SL0000-007-3801': 1,
  'SL0000-007-3891': 1,
  'SL0000-007-3981': 1,
  'SL0000-007-4071': 1,
  'SL0000-007-4161': 1,
  'SL0000-007-4251': 1,
  'SL0000-007-4341': 1,
  'SL0000-007-4431': 1,
  'SL0000-007-4521': 1,
  'SL0000-007-4611': 1,
  'SL0000-007-4701': 1,
  'SL0000-007-4791': 1,
  'SL0000-007-4881': 1,
  'SL0000-007-4971': 1,
  'SL0000-007-5061': 1,
  'SL0000-007-5151': 1,
  'SL0000-007-5241': 1,
  'SL0000-007-5331': 1,
  'SL0000-007-5421': 1,
  'SL0000-007-5511': 1,
  'SL0000-007-5601': 1,
  'SL0000-007-5691': 1,
  'SL0000-007-5781': 1,
  'SL0000-007-5871': 1,
  'SL0000-007-5961': 1,
  'SL0000-007-6051': 1,
  'SL0000-007-6141': 1,
  'SL0000-007-6231': 1,
  'SL0000-007-6321': 1,
  'SL0000-007-6411': 1,
  'SL0000-007-6501': 1,
  'SL0000-007-6591': 1,
  'SL0000-007-6681': 1,
  'SL0000-007-6771': 1,
  'SL0000-007-6861': 1,
  'SL0000-007-6951': 1,
  'SL0000-007-7041': 1,
  'SL0000-007-7131': 1,
  'SL0000-007-7221': 1,
  'SL0000-007-7311': 1,
  'SL0000-007-7401': 1,
  'SL0000-007-7491': 1,
  'SL0000-007-7581': 1,
  'SL0000-007-7671': 1,
  'SL0000-007-7761': 1,
  'SL0000-007-7851': 1,
  'SL0000-007-7941': 1,
  'SL0000-007-8031': 1,
  'SL0000-007-8121': 1,
  'SL0000-007-8211': 1,
  'SL0000-007-8301': 1,
  'SL0000-007-8391': 1,
  'SL0000-007-8481': 1,
  'SL0000-007-8571': 1,
  'SL0000-007-8661': 1,
  'SL0000-007-8751': 1,
  'SL0000-007-8841': 1,
  'SL0000-007-8931': 1,
  'SL0000-007-9021': 1,
  'SL0000-007-9111': 1,
  'SL0000-007-9201': 1,
  'SL0000-007-9291': 1,
  'SL0000-007-9381': 1,
  'SL0000-007-9471': 1,
  'SL0000-007-9561': 1,
  'SL0000-007-9651': 1,
  'SL0000-007-9741': 1,
  'SL0000-007-9831': 1,
  'SL0000-007-9921': 1,
  'SL0000-008-0011': 1,
  'SL0000-008-0101': 1,
  'SL0000-008-0191': 1,
  'SL0000-008-0281': 1,
  'SL0000-008-0371': 1,
  'SL0000-008-0461': 1,
  'SL0000-008-0551': 1,
  'SL0000-008-0641': 1,
  'SL0000-008-0731': 1,
  'SL0000-008-0911': 1,
  'SL0000-008-1001': 1,
  'SL0000-008-1091': 1,
  'SL0000-008-1181': 1,
  'SL0000-008-1271': 1,
  'SL0000-008-1361': 1,
  'SL0000-008-1451': 1,
  'SL0000-008-5591': 1,
  'SL0000-008-8291': 1,
  'SL0000-008-8381': 1,
  'SL0000-008-8471': 1,
  'SL0000-008-8561': 1,
  'SL0000-008-8651': 1,
  'SL0000-008-8741': 1,
  'SL0000-008-8831': 1,
  'SL0000-008-8921': 1,
  'SL0000-008-9011': 1,
  'SL0000-008-9101': 1,
  'SL0000-008-9102': 1,
  'SL0000-008-9191': 1,
  'SL0000-008-9281': 1,
  'SL0000-008-9282': 1,
  'SL0000-008-9371': 1,
  'SL0000-008-9461': 1,
  'SL0000-008-9551': 1,
  'SL0000-008-9552': 1,
  'SL0000-008-9641': 1,
  'SL0000-008-9731': 1,
  'SL0000-008-9821': 1,
  'SL0000-008-9822': 1,
  'SL0000-008-9911': 1,
  'SL0000-009-0001': 1,
  'SL0000-009-0091': 1,
  'SL0000-009-0181': 1,
  'SL0000-009-0271': 1,
  'SL0000-009-0361': 1,
  'SL0000-009-0451': 1,
  'SL0000-009-0541': 1,
  'SL0000-009-0631': 1,
  'SL0000-009-0721': 1,
  'SL0000-009-0811': 1,
  'SL0000-009-0901': 1,
  'SL0000-009-0902': 1,
  'SL0000-009-0991': 1,
  'SL0000-009-1081': 1,
  'SL0000-009-1171': 1,
  'SL0000-009-1172': 1,
  'SL0000-009-1261': 1,
  'SL0000-009-1351': 1,
  'SL0000-009-1441': 1,
  'SL0000-009-1531': 1,
  'SL0000-009-1621': 1,
  'SL0000-009-1711': 1,
  'SL0000-009-1801': 1,
  'SL0000-009-1891': 1,
  'SL0000-009-1981': 1,
  'SL0000-009-2071': 1,
  'SL0000-009-5131': 1,
  'SL0000-009-5221': 1,
  'SL0000-009-5311': 1,
  'SL0000-009-5401': 1,
  'SL0000-009-5491': 1,
  'SL0000-009-5581': 1,
  'SL0000-009-5671': 1,
  'SL0000-009-5851': 1,
  'SL0000-009-5941': 1,
  'SL0000-009-6031': 1,
  'SL0000-009-6121': 1,
  'SL0000-009-6211': 1,
  'SL0000-009-6301': 1,
  'SL0000-009-6391': 1,
  'SL0000-009-6481': 1,
  'SL0000-009-6571': 1,
  'SL0000-009-6661': 1,
  'SL0000-009-6751': 1,
  'SL0000-009-6841': 1,
  'SL0000-009-6931': 1,
  'SL0000-009-7021': 1,
  'SL0000-009-7111': 1,
  'SL0000-009-7201': 1,
  'SL0000-009-7291': 1,
  'SL0000-009-7381': 1,
  'SL0000-009-7471': 1,
  'SL0000-009-7561': 1,
  'SL0000-009-7651': 1,
  'SL0000-009-7741': 1,
  'SL0000-009-8011': 1,
  'SL0000-009-8101': 1,
  'SL0000-009-8191': 1,
  'SL0000-009-8281': 1,
  'SL0000-009-8282': 1,
  'SL0000-009-8371': 1,
  'SL0000-009-8461': 1,
  'SL0000-009-8551': 1,
  'SL0000-009-8641': 1,
  'SL0000-009-8731': 1,
  'SL0000-009-9001': 1,
  'SL0000-009-9091': 1,
  'SL0000-009-9181': 1,
  'SL0000-009-9271': 1,
  'SL0000-009-9361': 1,
  'SL0000-009-9451': 1,
  'SL0000-009-9541': 1,
  'SL0000-009-9631': 1,
  'SL0000-009-9721': 1,
  'SL0000-009-9811': 1,
  'SL0000-009-9901': 1,
  'SL0000-009-9991': 1,
  'SL0000-010-0081': 1,
  'SL0000-010-0171': 1,
  'SL0000-010-0261': 1,
  'SL0000-010-0351': 1,
  'SL0000-010-0441': 1,
  'SL0000-010-0531': 1,
  'SL0000-010-0621': 1,
  'SL0000-010-0711': 1,
  'SL0000-010-0801': 1,
  'SL0000-010-0891': 1,
  'SL0000-010-0981': 1,
  'SL0000-010-1071': 1,
  'SL0000-010-1161': 1,
  'SL0000-010-1251': 1,
  'SL0000-010-1341': 1,
  'SL0000-010-6111': 1,
  'SL0000-010-6112': 1,
  'SL0000-010-6201': 1,
  'SL0000-010-6291': 1,
  'SL0000-010-6381': 1,
  'SL0000-010-6471': 1,
  'SL0000-010-6561': 1,
  'SL0000-010-6651': 1,
  'SL0000-010-6741': 1,
  'SL0000-010-6831': 1,
  'SL0000-010-6921': 1,
  'SL0000-010-7011': 1,
  'SL0000-010-7101': 1,
  'SL0000-010-7191': 1,
  'SL0000-010-7281': 1,
  'SL0000-010-7371': 1,
  'SL0000-010-7461': 1,
  'SL0000-010-7551': 1,
  'SL0000-010-7641': 1,
  'SL0000-010-8451': 1,
  'SL0000-010-8541': 1,
  'SL0000-010-8631': 1,
  'SL0000-010-8632': 1,
  'SL0000-010-8721': 1,
  'SL0000-010-8901': 1,
  'SL0000-010-8902': 1,
  'SL0000-010-8991': 1,
  'SL0000-010-9081': 1,
  'SL0000-010-9082': 1,
  'SL0000-010-9171': 1,
  'SL0000-010-9261': 1,
  'SL0000-010-9351': 1,
  'SL0000-010-9441': 1,
  'SL0000-010-9531': 1,
  'SL0000-010-9621': 1,
  'SL0000-010-9711': 1,
  'SL0000-010-9801': 1,
  'SL0000-010-9891': 1,
  'SL0000-010-9892': 1,
  'SL0000-010-9981': 1,
  'SL0000-011-1421': 1,
  'SL0000-011-1422': 1,
  'SL0000-011-1511': 1,
  'SL0000-011-1601': 1,
  'SL0000-011-1691': 1,
  'SL0000-011-1781': 1,
  'SL0000-011-1871': 1,
  'SL0000-011-1961': 1,
  'SL0000-011-2051': 1,
  'SL0000-011-2141': 1,
  'SL0000-011-2231': 1,
  'SL0000-011-2321': 1,
  'SL0000-011-2411': 1,
  'SL0000-011-2501': 1,
  'SL0000-011-2591': 1,
  'SL0000-011-2681': 1,
  'SL0000-011-2771': 1,
  'SL0000-011-2861': 1,
  'SL0000-011-2951': 1,
  'SL0000-011-3041': 1,
  'SL0000-011-3131': 1,
  'SL0000-011-3221': 1,
  'SL0000-011-3311': 1,
  'SL0000-011-3401': 1,
  'SL0000-011-3491': 1,
  'SL0000-011-3581': 1,
  'SL0000-011-3671': 1,
  'SL0000-011-3761': 1,
  'SL0000-011-3851': 1,
  'SL0000-011-4031': 1,
  'SL0000-011-4121': 1,
  'SL0000-011-4211': 1,
  'SL0000-011-4301': 1,
  'SL0000-011-4391': 1,
  'SL0000-011-4481': 1,
  'SL0000-011-4571': 1,
  'SL0000-011-4661': 1,
  'SL0000-011-4751': 1,
  'SL0000-011-4841': 1,
  'SL0000-011-4931': 1,
  'SL0000-011-5201': 1,
  'SL0000-011-5291': 1,
  'SL0000-011-5381': 1,
  'SL0000-011-5471': 1,
  'SL0000-011-5561': 1,
  'SL0000-011-5651': 1,
  'SL0000-011-5741': 1,
  'SL0000-011-5831': 1,
  'SL0000-011-5921': 1,
  'SL0000-011-6011': 1,
  'SL0000-011-6101': 1,
  'SL0000-011-6191': 1,
  'SL0000-011-6281': 1,
  'SL0000-011-6371': 1,
  'SL0000-011-6461': 1,
  'SL0000-011-6551': 1,
  'SL0000-011-6641': 1,
  'SL0000-011-6731': 1,
  'SL0000-011-6821': 1,
  'SL0000-011-6911': 1,
  'SL0000-011-7001': 1,
  'SL0000-011-7091': 1,
  'SL0000-011-7181': 1,
  'SL0000-011-7271': 1,
  'SL0000-011-7361': 1,
  'SL0000-011-7451': 1,
  'SL0000-011-7541': 1,
  'SL0000-011-7631': 1,
  'SL0000-011-7721': 1,
  'SL0000-011-7811': 1,
  'SL0000-011-7901': 1,
  'SL0000-011-7991': 1,
  'SL0000-011-8081': 1,
  'SL0000-011-8171': 1,
  'SL0000-011-8261': 1,
  'SL0000-011-8351': 1,
  'SL0000-011-8441': 1,
  'SL0000-011-8531': 1,
  'SL0000-011-8621': 1,
  'SL0000-011-8711': 1,
  'SL0000-011-8801': 1,
  'SL0000-011-8891': 1,
  'SL0000-011-8981': 1,
  'SL0000-011-9071': 1,
  'SL0000-011-9161': 1,
  'SL0000-011-9251': 1,
  'SL0000-011-9341': 1,
  'SL0000-011-9431': 1,
  'SL0000-011-9521': 1,
  'SL0000-011-9611': 1,
  'SL0000-011-9701': 1,
  'SL0000-011-9791': 1,
  'SL0000-011-9881': 1,
  'SL0000-011-9971': 1,
  'SL0000-012-0061': 1,
  'SL0000-012-0151': 1,
  'SL0000-012-0241': 1,
  'SL0000-012-0241-1': 1,
  'SL0000-012-0331': 1,
  'SL0000-012-0421': 1,
  'SL0000-012-0511': 1,
  'SL0000-012-0601': 1,
  'SL0000-012-0691': 1,
  'SL0000-012-0781': 1,
  'SL0000-012-0781-1': 1,
  'SL0000-012-0871': 1,
  'SL0000-012-0961': 1,
  'SL0000-012-1051': 1,
  'SL0000-012-1141': 1,
  'SL0000-012-1231': 1,
  'SL0000-012-1321': 1,
  'SL0000-012-1411': 1,
  'SL0000-012-1501': 1,
  'SL0000-012-1502': 1,
  'SL0000-012-1591': 1,
  'SL0000-012-1771': 1,
  'SL0000-012-1772': 1,