In [9]:
import os
from nwtrace import *
import pandas as pd
import geopandas as gpd

from pathlib import Path

In [10]:
lines = Path('data/more/full_sewers.geojson')
nodes = Path('data/more/all_node_connections.geojson')

lines_gdf = gpd.read_file(lines)
nodes_gdf = gpd.read_file(nodes)

nodes_gdf = nodes_gdf.to_crs(lines_gdf.crs)

In [23]:
multiple = True
upstream_only = False
downstream_only = False
verbose = True

sewer_id_field = 'FACILITYID'
upstream_field = 'FROMMH'
downstream_field = 'TOMH'

outfall_file = 'data/more/BC_outfalls.csv'
id_field = 'Asset Identification'

outfalls = pd.read_csv(outfall_file)[id_field].tolist()

target_endpoints = outfalls

outputname_extra = "allBC_"
output_dir = f"./out"
if not os.path.exists(output_dir):
    os.mkdir(output_dir)

result = []

sewershed = NWTrace(
    network=lines_gdf,
    id_field=sewer_id_field,
    upstream_field = upstream_field,
    downstream_field = downstream_field,
    verbose=verbose,
    output_dir=output_dir,
)

# additional connections
fittings = gpd.read_file("data/more/fitting_connections.geojson")
nodes_up = (fittings[["FACILITYID", "TO_FIXED"]]
            .dropna(subset=["FACILITYID", "TO_FIXED"]) # remove rows with None values
            .rename(columns={"FACILITYID": 'node_id', "TO_FIXED": 'segment_id'})
            .to_dict(orient="records"))

sewershed.add_upstream_nodes(nodes_up)


node_lookup, seg_lookup = sewershed.get_lookup_tables()
dir_node_lookup, dir_seg_lookup = sewershed.get_directional_lookup_tables()

Added 5245 node-segment connection(s)
Created 627 new node(s)
Created 374 new segment(s).

In [12]:
errors = utils.verify_network_geometry(
    lines=lines_gdf,
    points=nodes_gdf,
    segment_lookup=seg_lookup,
    line_id_field="FACILITYID",
    point_id_field="FACILITYID",
    threshold=100
)
errors

100%|██████████| 169323/169323 [00:01<00:00, 104993.23it/s]

1176 Errors Found
Average Distance 0.14510461119443013 units

[{'node_id': 'MH5212822131',
  'segment_id': 'SL0000-001-5481',
  'error_t': 'missing node',
  'error_msg': 'node MH5212822131 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((322146.483 4852349.718, 322151.524 4852358.259, 322152.94...>},
 {'node_id': 'MH5151728331',
  'segment_id': 'SL0000-017-3071',
  'error_t': 'missing node',
  'error_msg': 'node MH5151728331 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((328347.352 4851739.48, 328336.356 4851748.668))>},
 {'node_id': 'MH5194926776',
  'segment_id': 'SL0000-027-4231',
  'error_t': 'missing node',
  'error_msg': 'node MH5194926776 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((326791.821 4852171.698, 326795.787 4852171.919))>},
 {'node_id': 'MH5008926783',
  'segment_id': 'SL0000-027-9001',
  'error_t': 'missing node',
  'error_msg': 'node MH5008926783 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((326799.977 4850308.313, 326792.018 4850319.971))>},
 {'node_id': 'MH4983723191-1',
  'segment_id': 'SL0000-028-8451',
  'error_t': 'missing node',
  'error_msg': 'node MH4983723191-1 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((323108.835 4850029.195, 323124.19 4850033.954, 323190.186...>},
 {'node_id': 'MH4828320461',
  'segment_id': 'SL0000-029-2911',
  'error_t': 'missing node',
  'error_msg': 'node MH4828320461 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((320477.662 4848505.531, 320482.413 4848499.232, 320485.43...>},
 {'node_id': 'MH4812924865',
  'segment_id': 'SL0000-029-7541',
  'error_t': 'missing node',
  'error_msg': 'node MH4812924865 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((324888.987 4848348.06, 324880.73 4848350.805))>},
 {'node_id': 'MH4250626429',
  'segment_id': 'SL0000-042-5881',
  'error_t': 'missing node',
  'error_msg': 'node MH4250626429 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((326451.975 4842735.253, 326445.106 4842727.739))>},
 {'node_id': 'MH5146426863',
  'segment_id': 'SL0000-051-0751',
  'error_t': 'missing node',
  'error_msg': 'node MH5146426863 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((326878.571 4851686.741, 326871.91 4851681.5, 326868.956 4...>},
 {'node_id': 'MH4905120850',
  'segment_id': 'SL0000-051-3271',
  'error_t': 'missing node',
  'error_msg': 'node MH4905120850 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((320865.763 4849273.919, 320863.331 4849283.227))>},
 {'node_id': 'MH4896120743',
  'segment_id': 'SL0000-051-3631',
  'error_t': 'missing node',
  'error_msg': 'node MH4896120743 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((320759.019 4849183.283, 320750.701 4849189.991, 320748.44...>},
 {'node_id': 'MH4692229329',
  'segment_id': 'SL0000-051-6691',
  'error_t': 'missing node',
  'error_msg': 'node MH4692229329 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((329345.047 4847144.615, 329334.35 4847144.692))>},
 {'node_id': 'MH4938033918',
  'segment_id': 'SL0000-052-2181',
  'error_t': 'missing node',
  'error_msg': 'node MH4938033918 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((333934.016 4849603.279, 333924 4849599.731))>},
 {'node_id': 'MH4261821628',
  'segment_id': 'SL0000-053-3351',
  'error_t': 'missing node',
  'error_msg': 'node MH4261821628 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((321644.317 4842840.286, 321665.698 4842827.421))>},
 {'node_id': 'MH4535823484',
  'segment_id': 'SL1000-000-8741',
  'error_t': 'missing node',
  'error_msg': 'node MH4535823484 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((323502.581 4845572.868, 323497.829 4845562.407))>},
 {'node_id': 'MH5012218977',
  'segment_id': 'SL1000-002-3231',
  'error_t': 'missing node',
  'error_msg': 'node MH5012218977 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((318992.231 4850344.329, 319004.267 4850352.425))>},
 {'node_id': 'OF4746527497',
  'segment_id': 'SL1000-003-0431',
  'error_t': 'missing node',
  'error_msg': 'node OF4746527497 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((327507.925 4847693.657, 327513.493 4847686.038))>},
 {'node_id': 'MH5187821974',
  'segment_id': 'SL1000-014-4011',
  'error_t': 'missing node',
  'error_msg': 'node MH5187821974 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((321989.358 4852099.981, 321981.74 4852093.163, 321979.749...>},
 {'node_id': 'MH4872126475',
  'segment_id': 'SL1000-016-7861',
  'error_t': 'missing node',
  'error_msg': 'node MH4872126475 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((326491.137 4848943.594, 326461.199 4848948.479, 326456.02...>},
 {'node_id': 'MH499852269-1',
  'segment_id': 'SL1000-028-7652',
  'error_t': 'missing node',
  'error_msg': 'node MH499852269-1 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((322670.154 4850270.476, 322697.321 4850228.577, 322699.35...>},
 {'node_id': 'MH4833724788',
  'segment_id': 'SL1000-029-7371',
  'error_t': 'missing node',
  'error_msg': 'node MH4833724788 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((324789.517 4848561.069, 324804.205 4848559.067))>},
 {'node_id': 'MH3946821961',
  'segment_id': 'SL1000-039-7811',
  'error_t': 'missing node',
  'error_msg': 'node MH3946821961 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((321976.46 4839690.282, 321975.863 4839678.587, 321975.736...>},
 {'node_id': 'MH4540220185A',
  'segment_id': 'SL1000-039-8621',
  'error_t': 'missing node',
  'error_msg': 'node MH4540220185A does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((320168.915 4845729.539, 320175.121 4845708.637, 320197.31...>},
 {'node_id': 'MH3943822013',
  'segment_id': 'SL1000-042-1931',
  'error_t': 'missing node',
  'error_msg': 'node MH3943822013 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((322030.459 4839657.45, 322031.909 4839669.135))>},
 {'node_id': 'MH5143626855',
  'segment_id': 'SL1000-051-0761',
  'error_t': 'missing node',
  'error_msg': 'node MH5143626855 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((326870.332 4851658.401, 326867.695 4851678.184))>},
 {'node_id': 'MH4828220458',
  'segment_id': 'SL1000-051-2921',
  'error_t': 'missing node',
  'error_msg': 'node MH4828220458 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((320474.43 4848504.326, 320476.565 4848497.348))>},
 {'node_id': 'MH4888720468',
  'segment_id': 'SL1000-051-3101',
  'error_t': 'missing node',
  'error_msg': 'node MH4888720468 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((320484.295 4849110.089, 320490.019 4849116.532, 320492.31...>},
 {'node_id': 'MH4937833918',
  'segment_id': 'SL1000-052-2191',
  'error_t': 'missing node',
  'error_msg': 'node MH4937833918 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((333934.346 4849601.401, 333923.26 4849598.005))>},
 {'node_id': 'MH5028426110',
  'segment_id': 'SL1000-053-0921',
  'error_t': 'missing node',
  'error_msg': 'node MH5028426110 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((326126.181 4850507.006, 326141.446 4850502.486))>},
 {'node_id': 'MH4133022254',
  'segment_id': 'SL1000-053-7681',
  'error_t': 'missing node',
  'error_msg': 'node MH4133022254 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((322269.944 4841552.776, 322263.058 4841533.358))>},
 {'node_id': 'MH5165818732',
  'segment_id': 'SL102066',
  'error_t': 'missing node',
  'error_msg': 'node MH5165818732 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((318747.563 4851880.067, 318759.635 4851876.698))>},
 {'node_id': 'MH2010179',
  'segment_id': 'SL110169',
  'error_t': 'missing node',
  'error_msg': 'node MH2010179 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((317738.122 4834895.029, 317735.327 4834907.094))>},
 {'node_id': 'MH3589316450',
  'segment_id': 'SL110267',
  'error_t': 'missing node',
  'error_msg': 'node MH3589316450 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((316468.001 4836132.084, 316466.565 4836115.937))>},
 {'node_id': 'MH2010446',
  'segment_id': 'SL110439',
  'error_t': 'spatial',
  'error_msg': 'node MH2010446 is more than 100 units from segment SL110439',
  'dist': 6381.532408153319,
  'geometry': <MULTILINESTRING ((304220.987 4841714.053, 304216.557 4841738.15, 304212.529...>},
 {'node_id': 'MH2010446',
  'segment_id': 'SL110440',
  'error_t': 'spatial',
  'error_msg': 'node MH2010446 is more than 100 units from segment SL110440',
  'dist': 6464.7814008682535,
  'geometry': <MULTILINESTRING ((304205.224 4841799.791, 304191.672 4841811.502))>},
 {'node_id': 'CN4931',
  'segment_id': 'SL110441',
  'error_t': 'spatial',
  'error_msg': 'node CN4931 is more than 100 units from segment SL110441',
  'dist': 12449.602404046625,
  'geometry': <MULTILINESTRING ((304915.635 4829264.625, 304804.519 4829231))>},
 {'node_id': 'CN10713',
  'segment_id': 'SL110469',
  'error_t': 'missing node',
  'error_msg': 'node CN10713 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((306504.698 4845937.329, 306505.117 4845929.826, 306505.37...>},
 {'node_id': 'MH2010675',
  'segment_id': 'SL110640',
  'error_t': 'missing node',
  'error_msg': 'node MH2010675 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((296459.116 4840651.323, 296450.97 4840605.981))>},
 {'node_id': 'MH2010970',
  'segment_id': 'SL110922',
  'error_t': 'spatial',
  'error_msg': 'node MH2010970 is more than 100 units from segment SL110922',
  'dist': 5101.466683670974,
  'geometry': <MULTILINESTRING ((302025.529 4833627.248, 302054.792 4833669.434))>},
 {'node_id': 'MH2010970',
  'segment_id': 'SL110923',
  'error_t': 'spatial',
  'error_msg': 'node MH2010970 is more than 100 units from segment SL110923',
  'dist': 5111.574342441547,
  'geometry': <MULTILINESTRING ((302054.792 4833669.434, 302088.948 4833716.465))>},
 {'node_id': 'MH2011085',
  'segment_id': 'SL111144',
  'error_t': 'missing node',
  'error_msg': 'node MH2011085 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((312764.529 4847060.315, 312761.492 4847068.166))>},
 {'node_id': 'MH5385622559',
  'segment_id': 'SL1400',
  'error_t': 'missing node',
  'error_msg': 'node MH5385622559 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((322574.806 4854078.494, 322584.27 4854079.603))>},
 {'node_id': 'MH3011630',
  'segment_id': 'SL1401227-1',
  'error_t': 'missing node',
  'error_msg': 'node MH3011630 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((311780.21 4842535.01, 311799.794 4842541.284))>},
 {'node_id': 'MH4071213633',
  'segment_id': 'SL1405680',
  'error_t': 'missing node',
  'error_msg': 'node MH4071213633 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((313650.971 4840930.345, 313674.99 4840846.653))>},
 {'node_id': 'MH4075513743',
  'segment_id': 'SL1409026',
  'error_t': 'missing node',
  'error_msg': 'node MH4075513743 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((313770.889 4840980.731, 313837.29 4840998.73))>},
 {'node_id': 'MH3978214622',
  'segment_id': 'SL1409933',
  'error_t': 'missing node',
  'error_msg': 'node MH3978214622 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((314638.377 4840004.429, 314700.236 4840021.719))>},
 {'node_id': 'MH3978214622',
  'segment_id': 'SL1410523',
  'error_t': 'missing node',
  'error_msg': 'node MH3978214622 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((314605.278 4839994.721, 314638.377 4840004.429))>},
 {'node_id': 'MH3893013894',
  'segment_id': 'SL1410923',
  'error_t': 'missing node',
  'error_msg': 'node MH3893013894 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((313909.731 4839152.146, 313930.677 4839084.526))>},
 {'node_id': 'MH3893013894',
  'segment_id': 'SL1410924',
  'error_t': 'missing node',
  'error_msg': 'node MH3893013894 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((313889.081 4839220.398, 313909.731 4839152.146))>},
 {'node_id': 'MH3978414620',
  'segment_id': 'SL1410970',
  'error_t': 'missing node',
  'error_msg': 'node MH3978414620 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((314559.529 4839984.136, 314632.521 4840005.106, 314636.47...>},
 {'node_id': 'MH3978414620',
  'segment_id': 'SL1410971',
  'error_t': 'missing node',
  'error_msg': 'node MH3978414620 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((314636.479 4840006.243, 314647.337 4840009.298))>},
 {'node_id': 'MH5302022634',
  'segment_id': 'SL1415',
  'error_t': 'missing node',
  'error_msg': 'node MH5302022634 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((322649.66 4853241.82, 322652.73 4853231.318))>},
 {'node_id': 'JP5428131293',
  'segment_id': 'SL1425515',
  'error_t': 'missing node',
  'error_msg': 'node JP5428131293 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((319421.733 4837012.668, 319408.035 4837024.683))>},
 {'node_id': 'CB5503039990',
  'segment_id': 'SL1425682',
  'error_t': 'missing node',
  'error_msg': 'node CB5503039990 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((319467.443 4837177.013, 319458.7 4837128.055))>},
 {'node_id': 'MH3584318439',
  'segment_id': 'SL1426097-1',
  'error_t': 'spatial',
  'error_msg': 'node MH3584318439 is more than 100 units from segment SL1426097-1',
  'dist': 112.51206523787347,
  'geometry': <MULTILINESTRING ((318489.389 4835958.492, 318493.927 4835944.012))>},
 {'node_id': 'MH3589316450',
  'segment_id': 'SL1427092',
  'error_t': 'missing node',
  'error_msg': 'node MH3589316450 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((316466.565 4836115.937, 316480.998 4836083.627))>},
 {'node_id': 'CB3569416470',
  'segment_id': 'SL1427843',
  'error_t': 'missing node',
  'error_msg': 'node CB3569416470 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((316486.444 4835916.099, 316441.915 4835906.477))>},
 {'node_id': 'MH3568517226',
  'segment_id': 'SL1427871',
  'error_t': 'missing node',
  'error_msg': 'node MH3568517226 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((317242.583 4835908.037, 317238.552 4835908.849))>},
 {'node_id': 'MH3568217215',
  'segment_id': 'SL1427872',
  'error_t': 'missing node',
  'error_msg': 'node MH3568217215 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((317231.438 4835904.578, 317232.203 4835904.606, 317233.01...>},
 {'node_id': 'MH3521018652',
  'segment_id': 'SL1427929',
  'error_t': 'missing node',
  'error_msg': 'node MH3521018652 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((318802.011 4835195.816, 318799.716 4835190.143, 318798.97...>},
 {'node_id': 'MH3557618891',
  'segment_id': 'SL1428002',
  'error_t': 'missing node',
  'error_msg': 'node MH3557618891 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((318928.772 4835727.359, 318906.844 4835798.792))>},
 {'node_id': 'MH3562818510',
  'segment_id': 'SL1428080',
  'error_t': 'missing node',
  'error_msg': 'node MH3562818510 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((318503.159 4835925.002, 318511.246 4835899.964, 318512.01...>},
 {'node_id': 'MH3602709890',
  'segment_id': 'SL1440132',
  'error_t': 'missing node',
  'error_msg': 'node MH3602709890 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((309980.555 4836271.931, 309980.076 4836271.787, 309906.23...>},
 {'node_id': 'MH3602709890',
  'segment_id': 'SL1440134',
  'error_t': 'missing node',
  'error_msg': 'node MH3602709890 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((309906.238 4836249.546, 309905.759 4836249.401, 309834.29...>},
 {'node_id': 'MH3552710687',
  'segment_id': 'SL1443653',
  'error_t': 'missing node',
  'error_msg': 'node MH3552710687 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((310697.675 4835764.737, 310702.855 4835749.579))>},
 {'node_id': 'MH3493907289',
  'segment_id': 'SL1448880',
  'error_t': 'missing node',
  'error_msg': 'node MH3493907289 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((307292.936 4835197.474, 307305.165 4835161.816))>},
 {'node_id': 'JP3311007204',
  'segment_id': 'SL1453745',
  'error_t': 'missing node',
  'error_msg': 'node JP3311007204 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((307213.087 4833326.119, 307218.589 4833330.309))>},
 {'node_id': 'MH3353211991',
  'segment_id': 'SL1454288',
  'error_t': 'missing node',
  'error_msg': 'node MH3353211991 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((312007.076 4833754.454, 311987.508 4833748.997))>},
 {'node_id': 'MH3297108950',
  'segment_id': 'SL1454612',
  'error_t': 'missing node',
  'error_msg': 'node MH3297108950 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((308914.368 4833377.098, 308966.212 4833193.994))>},
 {'node_id': 'MH3331906660',
  'segment_id': 'SL1456739',
  'error_t': 'missing node',
  'error_msg': 'node MH3331906660 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((306675.925 4833542.552, 306696.042 4833541.306))>},
 {'node_id': 'MH3331906660',
  'segment_id': 'SL1456740',
  'error_t': 'missing node',
  'error_msg': 'node MH3331906660 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((306675.146 4833540.442, 306675.925 4833542.552))>},
 {'node_id': 'PS3207811773',
  'segment_id': 'SL1457059',
  'error_t': 'missing node',
  'error_msg': 'node PS3207811773 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((311789.291 4832300.618, 311794.88 4832274.719))>},
 {'node_id': 'PS3279307238',
  'segment_id': 'SL1457071',
  'error_t': 'missing node',
  'error_msg': 'node PS3279307238 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((307252.831 4833014.448, 307252.406 4833014.185, 307238.25...>},
 {'node_id': 'MH3297108950',
  'segment_id': 'SL1457625',
  'error_t': 'missing node',
  'error_msg': 'node MH3297108950 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((308966.212 4833193.994, 309041.676 4833175.389))>},
 {'node_id': 'PS3200011432',
  'segment_id': 'SL1457639',
  'error_t': 'missing node',
  'error_msg': 'node PS3200011432 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((311436.032 4832283.146, 311447.957 4832222.357))>},
 {'node_id': 'PS3200011432',
  'segment_id': 'SL1457640',
  'error_t': 'missing node',
  'error_msg': 'node PS3200011432 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((311447.957 4832222.357, 311455.565 4832196.727))>},
 {'node_id': 'PS3200011432',
  'segment_id': 'SL1457641',
  'error_t': 'missing node',
  'error_msg': 'node PS3200011432 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((311447.957 4832222.357, 311452.719 4832195.844))>},
 {'node_id': 'PS3200011432',
  'segment_id': 'SL1457642',
  'error_t': 'missing node',
  'error_msg': 'node PS3200011432 does not exist in dataset',
  'dist': -1,
  'geometry': <MULTILINESTRING ((311384.438 4832238.617, 311447.957 4832222.357))>},
 {'node_id': 'PS3207811773',
  'segment_id': 'SL1457644',
  'error_t': 'missing node',
  'error_msg': 'node PS3207811773 does not exist in dataset',

In [13]:
err_df = gpd.GeoDataFrame.from_dict(errors, geometry="geometry")
err_df = err_df.set_crs(lines_gdf.crs)

err_df.to_file("out/errors.gpkg", driver="GPKG", layer="errorsv1")

err_df

,node_id,segment_id,error_t,error_msg,dist,geometry
0,MH5212822131,SL0000-001-5481,missing node,node MH5212822131 does not exist in dataset,-1.0,"MULTILINESTRING ((322146.483 4852349.718, 3221..."
1,MH5151728331,SL0000-017-3071,missing node,node MH5151728331 does not exist in dataset,-1.0,"MULTILINESTRING ((328347.352 4851739.48, 32833..."
2,MH5194926776,SL0000-027-4231,missing node,node MH5194926776 does not exist in dataset,-1.0,"MULTILINESTRING ((326791.821 4852171.698, 3267..."
3,MH5008926783,SL0000-027-9001,missing node,node MH5008926783 does not exist in dataset,-1.0,"MULTILINESTRING ((326799.977 4850308.313, 3267..."
4,MH4983723191-1,SL0000-028-8451,missing node,node MH4983723191-1 does not exist in dataset,-1.0,"MULTILINESTRING ((323108.835 4850029.195, 3231..."
...,...,...,...,...,...,...
1171,None,SL4000-007,missing segment,segment SL4000-007 does not exist in dataset,-1.0,None
1172,None,SL110491,missing segment,segment SL110491 does not exist in dataset,-1.0,None
1173,None,SL1404719,missing segment,segment SL1404719 does not exist in dataset,-1.0,None
1174,None,SL2000-011,missing segment,segment SL2000-011 does not exist in dataset,-1.0,None
1175,None,SL4163521,missing segment,segment SL4163521 does not exist in dataset,-1.0,None

In [14]:
cons_err_df = err_df.groupby(["error_t"]).count()
cons_err_df

                 node_id  segment_id  error_msg  dist  geometry
error_t
missing node         789         789        789   789       789
missing segment        0         374        374   374         0
spatial               13          13         13    13        13

In [15]:
ids_dup = utils.count_duplicates(lines_gdf, "FACILITYID", minimum_count=0)
ids_dup

{'duplicate_count': {'SL0000-000-0091': 1,
  'SL0000-000-0181': 1,
  'SL0000-000-0271': 1,
  'SL0000-000-0361': 1,
  'SL0000-000-0451': 1,
  'SL0000-000-0541': 1,
  'SL0000-000-0631': 1,
  'SL0000-000-0721': 1,
  'SL0000-000-0722': 1,
  'SL0000-000-0811': 1,
  'SL0000-000-0901': 1,
  'SL0000-000-0991': 1,
  'SL0000-000-1081': 1,
  'SL0000-000-1171': 1,
  'SL0000-000-1261': 1,
  'SL0000-000-1351': 1,
  'SL0000-000-1441': 1,
  'SL0000-000-1531': 1,
  'SL0000-000-1621': 1,
  'SL0000-000-1711': 1,
  'SL0000-000-1801': 1,
  'SL0000-000-1891': 1,
  'SL0000-000-1981': 1,
  'SL0000-000-2071': 1,
  'SL0000-000-2161': 1,
  'SL0000-000-3961': 1,
  'SL0000-000-4051': 1,
  'SL0000-000-4141': 1,
  'SL0000-000-4231': 1,
  'SL0000-000-4232': 1,
  'SL0000-000-4321': 1,
  'SL0000-000-4411': 1,
  'SL0000-000-4501': 1,
  'SL0000-000-4591': 1,
  'SL0000-000-4681': 1,
  'SL0000-000-4771': 1,
  'SL0000-000-4861': 1,
  'SL0000-000-4951': 1,
  'SL0000-000-5041': 1,
  'SL0000-000-5131': 1,
  'SL0000-000-5221': 1,
  'SL0000-000-5311': 1,
  'SL0000-000-5401': 1,
  'SL0000-000-5491': 1,
  'SL0000-000-5671': 1,
  'SL0000-000-5761': 1,
  'SL0000-000-5851': 1,
  'SL0000-000-5941': 1,
  'SL0000-000-6031': 1,
  'SL0000-000-6121': 1,
  'SL0000-000-6211': 1,
  'SL0000-000-6301': 1,
  'SL0000-000-6391': 1,
  'SL0000-000-6571': 1,
  'SL0000-000-8371': 1,
  'SL0000-000-8461': 1,
  'SL0000-000-8551': 1,
  'SL0000-000-8641': 1,
  'SL0000-000-8731': 1,
  'SL0000-000-8732': 1,
  'SL0000-000-8821': 1,
  'SL0000-000-8911': 1,
  'SL0000-000-9001': 1,
  'SL0000-000-9091': 1,
  'SL0000-000-9181': 1,
  'SL0000-000-9271': 1,
  'SL0000-000-9361': 1,
  'SL0000-000-9451': 1,
  'SL0000-000-9541': 1,
  'SL0000-001-0531': 1,
  'SL0000-001-0621': 1,
  'SL0000-001-0711': 1,
  'SL0000-001-0801': 1,
  'SL0000-001-0891': 1,
  'SL0000-001-0981': 1,
  'SL0000-001-1071': 1,
  'SL0000-001-1161': 1,
  'SL0000-001-1251': 1,
  'SL0000-001-1341': 1,
  'SL0000-001-1431': 1,
  'SL0000-001-1521': 1,
  'SL0000-001-1522': 1,
  'SL0000-001-1611': 1,
  'SL0000-001-1612': 1,
  'SL0000-001-1701': 1,
  'SL0000-001-1702': 1,
  'SL0000-001-1791': 1,
  'SL0000-001-1792': 1,
  'SL0000-001-1881': 1,
  'SL0000-001-1882': 1,
  'SL0000-001-1971': 1,
  'SL0000-001-1972': 1,
  'SL0000-001-2061': 1,
  'SL0000-001-2062': 1,
  'SL0000-001-2151': 1,
  'SL0000-001-2152': 1,
  'SL0000-001-2241': 1,
  'SL0000-001-2331': 1,
  'SL0000-001-4491': 1,
  'SL0000-001-4581': 1,
  'SL0000-001-4671': 1,
  'SL0000-001-4761': 1,
  'SL0000-001-4851': 1,
  'SL0000-001-5301': 1,
  'SL0000-001-5391': 1,
  'SL0000-001-5481': 1,
  'SL0000-001-5571': 1,
  'SL0000-001-5661': 1,
  'SL0000-001-5751': 1,
  'SL0000-001-5841': 1,
  'SL0000-001-5931': 1,
  'SL0000-001-6021': 1,
  'SL0000-001-6111': 1,
  'SL0000-001-6201': 1,
  'SL0000-001-6291': 1,
  'SL0000-001-6381': 1,
  'SL0000-001-6471': 1,
  'SL0000-001-6561': 1,
  'SL0000-001-6651': 1,
  'SL0000-001-6741': 1,
  'SL0000-001-6831': 1,
  'SL0000-001-6921': 1,
  'SL0000-001-8721': 1,
  'SL0000-001-8811': 1,
  'SL0000-001-8901': 1,
  'SL0000-001-8902': 1,
  'SL0000-001-8991': 1,
  'SL0000-001-9081': 1,
  'SL0000-001-9171': 1,
  'SL0000-001-9261': 1,
  'SL0000-001-9351': 1,
  'SL0000-001-9441': 1,
  'SL0000-001-9442': 1,
  'SL0000-001-9531': 1,
  'SL0000-001-9532': 1,
  'SL0000-001-9621': 1,
  'SL0000-001-9711': 1,
  'SL0000-001-9801': 1,
  'SL0000-001-9891': 1,
  'SL0000-002-1511': 1,
  'SL0000-002-1601': 1,
  'SL0000-002-1602': 1,
  'SL0000-002-1691': 1,
  'SL0000-002-1781': 1,
  'SL0000-002-1871': 1,
  'SL0000-002-1961': 1,
  'SL0000-002-2051': 1,
  'SL0000-002-2141': 1,
  'SL0000-002-2231': 1,
  'SL0000-002-2321': 1,
  'SL0000-002-2411': 1,
  'SL0000-002-2501': 1,
  'SL0000-002-2591': 1,
  'SL0000-002-2681': 1,
  'SL0000-002-2771': 1,
  'SL0000-002-2861': 1,
  'SL0000-002-2951': 1,
  'SL0000-002-3041': 1,
  'SL0000-002-3131': 1,
  'SL0000-002-3221': 1,
  'SL0000-002-4661': 1,
  'SL0000-002-4751': 1,
  'SL0000-002-4841': 1,
  'SL0000-002-4931': 1,
  'SL0000-002-5021': 1,
  'SL0000-002-5111': 1,
  'SL0000-002-5201': 1,
  'SL0000-002-5291': 1,
  'SL0000-002-5291-1': 1,
  'SL0000-002-5381': 1,
  'SL0000-002-5471': 1,
  'SL0000-002-5651': 1,
  'SL0000-002-5741': 1,
  'SL0000-002-5831': 1,
  'SL0000-002-5921': 1,
  'SL0000-002-6011': 1,
  'SL0000-002-6101': 1,
  'SL0000-002-6191': 1,
  'SL0000-002-6281': 1,
  'SL0000-002-6371': 1,
  'SL0000-002-7991': 1,
  'SL0000-002-8531': 1,
  'SL0000-002-8621': 1,
  'SL0000-002-8711': 1,
  'SL0000-002-8801': 1,
  'SL0000-002-8891': 1,
  'SL0000-002-8981': 1,
  'SL0000-002-9071': 1,
  'SL0000-002-9161': 1,
  'SL0000-002-9251': 1,
  'SL0000-002-9341': 1,
  'SL0000-002-9431': 1,
  'SL0000-002-9521': 1,
  'SL0000-002-9611': 1,
  'SL0000-002-9701': 1,
  'SL0000-002-9791': 1,
  'SL0000-002-9881': 1,
  'SL0000-002-9971': 1,
  'SL0000-003-0061': 1,
  'SL0000-003-0151': 1,
  'SL0000-003-0241': 1,
  'SL0000-003-0331': 1,
  'SL0000-003-0421': 1,
  'SL0000-003-0511': 1,
  'SL0000-003-0601': 1,
  'SL0000-003-0691': 1,
  'SL0000-003-0781': 1,
  'SL0000-003-0871': 1,
  'SL0000-003-0961': 1,
  'SL0000-003-1051': 1,
  'SL0000-003-1141': 1,
  'SL0000-003-1231': 1,
  'SL0000-003-1321': 1,
  'SL0000-003-1411': 1,
  'SL0000-003-1501': 1,
  'SL0000-003-1591': 1,
  'SL0000-003-1681': 1,
  'SL0000-003-1771': 1,
  'SL0000-003-1861': 1,
  'SL0000-003-1951': 1,
  'SL0000-003-2041': 1,
  'SL0000-003-2131': 1,
  'SL0000-003-4831': 1,
  'SL0000-003-4921': 1,
  'SL0000-003-5011': 1,
  'SL0000-003-5101': 1,
  'SL0000-003-5191': 1,
  'SL0000-003-5281': 1,
  'SL0000-003-5371': 1,
  'SL0000-003-5461': 1,
  'SL0000-003-5551': 1,
  'SL0000-003-5641': 1,
  'SL0000-003-5731': 1,
  'SL0000-003-5821': 1,
  'SL0000-003-5911': 1,
  'SL0000-003-6001': 1,
  'SL0000-003-6091': 1,
  'SL0000-003-6181': 1,
  'SL0000-003-6271': 1,
  'SL0000-003-6361': 1,
  'SL0000-003-6451': 1,
  'SL0000-003-6541': 1,
  'SL0000-003-6631': 1,
  'SL0000-003-6721': 1,
  'SL0000-003-6811': 1,
  'SL0000-003-6901': 1,
  'SL0000-003-6991': 1,
  'SL0000-003-7081': 1,
  'SL0000-003-7171': 1,
  'SL0000-003-7261': 1,
  'SL0000-003-9151': 1,
  'SL0000-003-9241': 1,
  'SL0000-003-9331': 1,
  'SL0000-003-9421': 1,
  'SL0000-003-9511': 1,
  'SL0000-003-9601': 1,
  'SL0000-003-9691': 1,
  'SL0000-003-9781': 1,
  'SL0000-003-9871': 1,
  'SL0000-003-9961': 1,
  'SL0000-004-0051': 1,
  'SL0000-004-0141': 1,
  'SL0000-004-0231': 1,
  'SL0000-004-0321': 1,
  'SL0000-004-0411': 1,
  'SL0000-004-0501': 1,
  'SL0000-004-0591': 1,
  'SL0000-004-0681': 1,
  'SL0000-004-0771': 1,
  'SL0000-004-0951': 1,
  'SL0000-004-1041': 1,
  'SL0000-004-1131': 1,
  'SL0000-004-1221': 1,
  'SL0000-004-1311': 1,
  'SL0000-004-2931': 1,
  'SL0000-004-3021': 1,
  'SL0000-004-3111': 1,
  'SL0000-004-3201': 1,
  'SL0000-004-3291': 1,
  'SL0000-004-3381': 1,
  'SL0000-004-3471': 1,
  'SL0000-004-3561': 1,
  'SL0000-004-3651': 1,
  'SL0000-004-3741': 1,
  'SL0000-004-3831': 1,
  'SL0000-004-3921': 1,
  'SL0000-004-4011': 1,
  'SL0000-004-4101': 1,
  'SL0000-004-4191': 1,
  'SL0000-004-4281': 1,
  'SL0000-004-4371': 1,
  'SL0000-004-4461': 1,
  'SL0000-004-4551': 1,
  'SL0000-004-4641': 1,
  'SL0000-004-4731': 1,
  'SL0000-004-4821': 1,
  'SL0000-004-4911': 1,
  'SL0000-004-5001': 1,
  'SL0000-004-5091': 1,
  'SL0000-004-5181': 1,
  'SL0000-004-5271': 1,
  'SL0000-004-6531': 1,
  'SL0000-004-6621': 1,
  'SL0000-004-6711': 1,
  'SL0000-004-6801': 1,
  'SL0000-004-6891': 1,
  'SL0000-004-6981': 1,
  'SL0000-004-7071': 1,
  'SL0000-004-7161': 1,
  'SL0000-004-7251': 1,
  'SL0000-004-7341': 1,
  'SL0000-004-7431': 1,
  'SL0000-004-7521': 1,
  'SL0000-004-7611': 1,
  'SL0000-004-7701': 1,
  'SL0000-004-7791': 1,
  'SL0000-004-7881': 1,
  'SL0000-004-7971': 1,
  'SL0000-004-8061': 1,
  'SL0000-004-8151': 1,
  'SL0000-004-8241': 1,
  'SL0000-004-8331': 1,
  'SL0000-004-8421': 1,
  'SL0000-004-8511': 1,
  'SL0000-004-8601': 1,
  'SL0000-004-8691': 1,
  'SL0000-004-8781': 1,
  'SL0000-004-8871': 1,
  'SL0000-005-0221': 1,
  'SL0000-005-0311': 1,
  'SL0000-005-0401': 1,
  'SL0000-005-0491': 1,
  'SL0000-005-0581': 1,
  'SL0000-005-0671': 1,
  'SL0000-005-0761': 1,
  'SL0000-005-0851': 1,
  'SL0000-005-0941': 1,
  'SL0000-005-0942': 1,
  'SL0000-005-1031': 1,
  'SL0000-005-1121': 1,
  'SL0000-005-1211': 1,
  'SL0000-005-1301': 1,
  'SL0000-005-1391': 1,
  'SL0000-005-1481': 1,
  'SL0000-005-1571': 1,
  'SL0000-005-1661': 1,
  'SL0000-005-1751': 1,
  'SL0000-005-1841': 1,
  'SL0000-005-1931': 1,
  'SL0000-005-1932': 1,
  'SL0000-005-3191': 1,
  'SL0000-005-3461': 1,
  'SL0000-005-3462': 1,
  'SL0000-005-3551': 1,
  'SL0000-005-3641': 1,
  'SL0000-005-3731': 1,
  'SL0000-005-3821': 1,
  'SL0000-005-3822': 1,
  'SL0000-005-3911': 1,
  'SL0000-005-4091': 1,
  'SL0000-005-4181': 1,
  'SL0000-005-4271': 1,
  'SL0000-005-4361': 1,
  'SL0000-005-4362': 1,
  'SL0000-005-4451': 1,
  'SL0000-005-4541': 1,
  'SL0000-005-4631': 1,
  'SL0000-005-4721': 1,
  'SL0000-005-4722': 1,
  'SL0000-005-4811': 1,
  'SL0000-005-4901': 1,
  'SL0000-005-4991': 1,
  'SL0000-005-5081': 1,
  'SL0000-005-5171': 1,
  'SL0000-005-5261': 1,
  'SL0000-005-6791': 1,
  'SL0000-005-7691': 1,
  'SL0000-005-7781': 1,
  'SL0000-005-7871': 1,
  'SL0000-005-7961': 1,
  'SL0000-005-8411': 1,
  'SL0000-005-8501': 1,
  'SL0000-005-8591': 1,
  'SL0000-005-8681': 1,
  'SL0000-005-8771': 1,
  'SL0000-005-8861': 1,
  'SL0000-005-8951': 1,
  'SL0000-005-9041': 1,
  'SL0000-005-9131': 1,
  'SL0000-005-9221': 1,
  'SL0000-005-9311': 1,
  'SL0000-005-9401': 1,
  'SL0000-005-9491': 1,
  'SL0000-005-9581': 1,
  'SL0000-005-9671': 1,
  'SL0000-005-9761': 1,
  'SL0000-005-9851': 1,
  'SL0000-005-9941': 1,
  'SL0000-006-0031': 1,
  'SL0000-006-0121': 1,
  'SL0000-006-0211': 1,
  'SL0000-006-0301': 1,
  'SL0000-006-0391': 1,
  'SL0000-006-0481': 1,
  'SL0000-006-0571': 1,
  'SL0000-006-0661': 1,
  'SL0000-006-0751': 1,
  'SL0000-006-0841': 1,
  'SL0000-006-0931': 1,
  'SL0000-006-2821': 1,
  'SL0000-006-2911': 1,
  'SL0000-006-3001': 1,
  'SL0000-006-3091': 1,
  'SL0000-006-3181': 1,
  'SL0000-006-3271': 1,
  'SL0000-006-3272': 1,
  'SL0000-006-3361': 1,
  'SL0000-006-3451': 1,
  'SL0000-006-3541': 1,
  'SL0000-006-3631': 1,
  'SL0000-006-3721': 1,
  'SL0000-006-3811': 1,
  'SL0000-006-3901': 1,
  'SL0000-006-3991': 1,
  'SL0000-006-4081': 1,
  'SL0000-006-4171': 1,
  'SL0000-006-4261': 1,
  'SL0000-006-4262': 1,
  'SL0000-006-4351': 1,
  'SL0000-006-4441': 1,
  'SL0000-006-4531': 1,
  'SL0000-006-4621': 1,
  'SL0000-006-4711': 1,
  'SL0000-006-4801': 1,
  'SL0000-006-6691': 1,
  'SL0000-006-6871': 1,
  'SL0000-006-6961': 1,
  'SL0000-006-7051': 1,
  'SL0000-006-7141': 1,
  'SL0000-006-7231': 1,
  'SL0000-006-7321': 1,
  'SL0000-006-7411': 1,
  'SL0000-006-7501': 1,
  'SL0000-006-8491': 1,
  'SL0000-006-8581': 1,
  'SL0000-006-8671': 1,
  'SL0000-006-8761': 1,
  'SL0000-006-8851': 1,
  'SL0000-006-8941': 1,
  'SL0000-006-9031': 1,
  'SL0000-006-9121': 1,
  'SL0000-006-9301': 1,
  'SL0000-006-9391': 1,
  'SL0000-006-9481': 1,
  'SL0000-006-9571': 1,
  'SL0000-006-9661': 1,
  'SL0000-006-9751': 1,
  'SL0000-006-9841': 1,
  'SL0000-007-1101': 1,
  'SL0000-007-1371': 1,
  'SL0000-007-1551': 1,
  'SL0000-007-1641': 1,
  'SL0000-007-1731': 1,
  'SL0000-007-1821': 1,
  'SL0000-007-1911': 1,
  'SL0000-007-2001': 1,
  'SL0000-007-2091': 1,
  'SL0000-007-2271': 1,
  'SL0000-007-2901': 1,
  'SL0000-007-3261': 1,
  'SL0000-007-3351': 1,
  'SL0000-007-3441': 1,
  'SL0000-007-3531': 1,
  'SL0000-007-3711': 1,
  'SL0000-007-3801': 1,
  'SL0000-007-3891': 1,
  'SL0000-007-3981': 1,
  'SL0000-007-4071': 1,
  'SL0000-007-4161': 1,
  'SL0000-007-4251': 1,
  'SL0000-007-4341': 1,
  'SL0000-007-4431': 1,
  'SL0000-007-4521': 1,
  'SL0000-007-4611': 1,
  'SL0000-007-4701': 1,
  'SL0000-007-4791': 1,
  'SL0000-007-4881': 1,
  'SL0000-007-4971': 1,
  'SL0000-007-5061': 1,
  'SL0000-007-5151': 1,
  'SL0000-007-5241': 1,
  'SL0000-007-5331': 1,
  'SL0000-007-5421': 1,
  'SL0000-007-5511': 1,
  'SL0000-007-5601': 1,
  'SL0000-007-5691': 1,
  'SL0000-007-5781': 1,
  'SL0000-007-5871': 1,
  'SL0000-007-5961': 1,
  'SL0000-007-6051': 1,
  'SL0000-007-6141': 1,
  'SL0000-007-6231': 1,
  'SL0000-007-6321': 1,
  'SL0000-007-6411': 1,
  'SL0000-007-6501': 1,
  'SL0000-007-6591': 1,
  'SL0000-007-6681': 1,
  'SL0000-007-6771': 1,
  'SL0000-007-6861': 1,
  'SL0000-007-6951': 1,
  'SL0000-007-7041': 1,
  'SL0000-007-7131': 1,
  'SL0000-007-7221': 1,
  'SL0000-007-7311': 1,
  'SL0000-007-7401': 1,
  'SL0000-007-7491': 1,
  'SL0000-007-7581': 1,
  'SL0000-007-7671': 1,
  'SL0000-007-7761': 1,
  'SL0000-007-7851': 1,
  'SL0000-007-7941': 1,
  'SL0000-007-8031': 1,
  'SL0000-007-8121': 1,
  'SL0000-007-8211': 1,
  'SL0000-007-8301': 1,
  'SL0000-007-8391': 1,
  'SL0000-007-8481': 1,
  'SL0000-007-8571': 1,
  'SL0000-007-8661': 1,
  'SL0000-007-8751': 1,
  'SL0000-007-8841': 1,
  'SL0000-007-8931': 1,
  'SL0000-007-9021': 1,
  'SL0000-007-9111': 1,
  'SL0000-007-9201': 1,
  'SL0000-007-9291': 1,
  'SL0000-007-9381': 1,
  'SL0000-007-9471': 1,
  'SL0000-007-9561': 1,
  'SL0000-007-9651': 1,
  'SL0000-007-9741': 1,
  'SL0000-007-9831': 1,
  'SL0000-007-9921': 1,
  'SL0000-008-0011': 1,
  'SL0000-008-0101': 1,
  'SL0000-008-0191': 1,
  'SL0000-008-0281': 1,
  'SL0000-008-0371': 1,
  'SL0000-008-0461': 1,
  'SL0000-008-0551': 1,
  'SL0000-008-0641': 1,
  'SL0000-008-0731': 1,
  'SL0000-008-0911': 1,
  'SL0000-008-1001': 1,
  'SL0000-008-1091': 1,
  'SL0000-008-1181': 1,
  'SL0000-008-1271': 1,
  'SL0000-008-1361': 1,
  'SL0000-008-1451': 1,
  'SL0000-008-5591': 1,
  'SL0000-008-8291': 1,
  'SL0000-008-8381': 1,
  'SL0000-008-8471': 1,
  'SL0000-008-8561': 1,
  'SL0000-008-8651': 1,
  'SL0000-008-8741': 1,
  'SL0000-008-8831': 1,
  'SL0000-008-8921': 1,
  'SL0000-008-9011': 1,
  'SL0000-008-9101': 1,
  'SL0000-008-9102': 1,
  'SL0000-008-9191': 1,
  'SL0000-008-9281': 1,
  'SL0000-008-9282': 1,
  'SL0000-008-9371': 1,
  'SL0000-008-9461': 1,
  'SL0000-008-9551': 1,
  'SL0000-008-9552': 1,
  'SL0000-008-9641': 1,
  'SL0000-008-9731': 1,
  'SL0000-008-9821': 1,
  'SL0000-008-9822': 1,
  'SL0000-008-9911': 1,
  'SL0000-009-0001': 1,
  'SL0000-009-0091': 1,
  'SL0000-009-0181': 1,
  'SL0000-009-0271': 1,
  'SL0000-009-0361': 1,
  'SL0000-009-0451': 1,
  'SL0000-009-0541': 1,
  'SL0000-009-0631': 1,
  'SL0000-009-0721': 1,
  'SL0000-009-0811': 1,
  'SL0000-009-0901': 1,
  'SL0000-009-0902': 1,
  'SL0000-009-0991': 1,
  'SL0000-009-1081': 1,
  'SL0000-009-1171': 1,
  'SL0000-009-1172': 1,
  'SL0000-009-1261': 1,
  'SL0000-009-1351': 1,
  'SL0000-009-1441': 1,
  'SL0000-009-1531': 1,
  'SL0000-009-1621': 1,
  'SL0000-009-1711': 1,
  'SL0000-009-1801': 1,
  'SL0000-009-1891': 1,
  'SL0000-009-1981': 1,
  'SL0000-009-2071': 1,
  'SL0000-009-5131': 1,
  'SL0000-009-5221': 1,
  'SL0000-009-5311': 1,
  'SL0000-009-5401': 1,
  'SL0000-009-5491': 1,
  'SL0000-009-5581': 1,
  'SL0000-009-5671': 1,
  'SL0000-009-5851': 1,
  'SL0000-009-5941': 1,
  'SL0000-009-6031': 1,
  'SL0000-009-6121': 1,
  'SL0000-009-6211': 1,
  'SL0000-009-6301': 1,
  'SL0000-009-6391': 1,
  'SL0000-009-6481': 1,
  'SL0000-009-6571': 1,
  'SL0000-009-6661': 1,
  'SL0000-009-6751': 1,
  'SL0000-009-6841': 1,
  'SL0000-009-6931': 1,
  'SL0000-009-7021': 1,
  'SL0000-009-7111': 1,
  'SL0000-009-7201': 1,
  'SL0000-009-7291': 1,
  'SL0000-009-7381': 1,
  'SL0000-009-7471': 1,
  'SL0000-009-7561': 1,
  'SL0000-009-7651': 1,
  'SL0000-009-7741': 1,
  'SL0000-009-8011': 1,
  'SL0000-009-8101': 1,
  'SL0000-009-8191': 1,
  'SL0000-009-8281': 1,
  'SL0000-009-8282': 1,
  'SL0000-009-8371': 1,
  'SL0000-009-8461': 1,
  'SL0000-009-8551': 1,
  'SL0000-009-8641': 1,
  'SL0000-009-8731': 1,
  'SL0000-009-9001': 1,
  'SL0000-009-9091': 1,
  'SL0000-009-9181': 1,
  'SL0000-009-9271': 1,
  'SL0000-009-9361': 1,
  'SL0000-009-9451': 1,
  'SL0000-009-9541': 1,
  'SL0000-009-9631': 1,
  'SL0000-009-9721': 1,
  'SL0000-009-9811': 1,
  'SL0000-009-9901': 1,
  'SL0000-009-9991': 1,
  'SL0000-010-0081': 1,
  'SL0000-010-0171': 1,
  'SL0000-010-0261': 1,
  'SL0000-010-0351': 1,
  'SL0000-010-0441': 1,
  'SL0000-010-0531': 1,
  'SL0000-010-0621': 1,
  'SL0000-010-0711': 1,
  'SL0000-010-0801': 1,
  'SL0000-010-0891': 1,
  'SL0000-010-0981': 1,
  'SL0000-010-1071': 1,
  'SL0000-010-1161': 1,
  'SL0000-010-1251': 1,
  'SL0000-010-1341': 1,
  'SL0000-010-6111': 1,
  'SL0000-010-6112': 1,
  'SL0000-010-6201': 1,
  'SL0000-010-6291': 1,
  'SL0000-010-6381': 1,
  'SL0000-010-6471': 1,
  'SL0000-010-6561': 1,
  'SL0000-010-6651': 1,
  'SL0000-010-6741': 1,
  'SL0000-010-6831': 1,
  'SL0000-010-6921': 1,
  'SL0000-010-7011': 1,
  'SL0000-010-7101': 1,
  'SL0000-010-7191': 1,
  'SL0000-010-7281': 1,
  'SL0000-010-7371': 1,
  'SL0000-010-7461': 1,
  'SL0000-010-7551': 1,
  'SL0000-010-7641': 1,
  'SL0000-010-8451': 1,
  'SL0000-010-8541': 1,
  'SL0000-010-8631': 1,
  'SL0000-010-8632': 1,
  'SL0000-010-8721': 1,
  'SL0000-010-8901': 1,
  'SL0000-010-8902': 1,
  'SL0000-010-8991': 1,
  'SL0000-010-9081': 1,
  'SL0000-010-9082': 1,
  'SL0000-010-9171': 1,
  'SL0000-010-9261': 1,
  'SL0000-010-9351': 1,
  'SL0000-010-9441': 1,
  'SL0000-010-9531': 1,
  'SL0000-010-9621': 1,
  'SL0000-010-9711': 1,
  'SL0000-010-9801': 1,
  'SL0000-010-9891': 1,
  'SL0000-010-9892': 1,
  'SL0000-010-9981': 1,
  'SL0000-011-1421': 1,
  'SL0000-011-1422': 1,
  'SL0000-011-1511': 1,
  'SL0000-011-1601': 1,
  'SL0000-011-1691': 1,
  'SL0000-011-1781': 1,
  'SL0000-011-1871': 1,
  'SL0000-011-1961': 1,
  'SL0000-011-2051': 1,
  'SL0000-011-2141': 1,
  'SL0000-011-2231': 1,
  'SL0000-011-2321': 1,
  'SL0000-011-2411': 1,
  'SL0000-011-2501': 1,
  'SL0000-011-2591': 1,
  'SL0000-011-2681': 1,
  'SL0000-011-2771': 1,
  'SL0000-011-2861': 1,
  'SL0000-011-2951': 1,
  'SL0000-011-3041': 1,
  'SL0000-011-3131': 1,
  'SL0000-011-3221': 1,
  'SL0000-011-3311': 1,
  'SL0000-011-3401': 1,
  'SL0000-011-3491': 1,
  'SL0000-011-3581': 1,
  'SL0000-011-3671': 1,
  'SL0000-011-3761': 1,
  'SL0000-011-3851': 1,
  'SL0000-011-4031': 1,
  'SL0000-011-4121': 1,
  'SL0000-011-4211': 1,
  'SL0000-011-4301': 1,
  'SL0000-011-4391': 1,
  'SL0000-011-4481': 1,
  'SL0000-011-4571': 1,
  'SL0000-011-4661': 1,
  'SL0000-011-4751': 1,
  'SL0000-011-4841': 1,
  'SL0000-011-4931': 1,
  'SL0000-011-5201': 1,
  'SL0000-011-5291': 1,
  'SL0000-011-5381': 1,
  'SL0000-011-5471': 1,
  'SL0000-011-5561': 1,
  'SL0000-011-5651': 1,
  'SL0000-011-5741': 1,
  'SL0000-011-5831': 1,
  'SL0000-011-5921': 1,
  'SL0000-011-6011': 1,
  'SL0000-011-6101': 1,
  'SL0000-011-6191': 1,
  'SL0000-011-6281': 1,
  'SL0000-011-6371': 1,
  'SL0000-011-6461': 1,
  'SL0000-011-6551': 1,
  'SL0000-011-6641': 1,
  'SL0000-011-6731': 1,
  'SL0000-011-6821': 1,
  'SL0000-011-6911': 1,
  'SL0000-011-7001': 1,
  'SL0000-011-7091': 1,
  'SL0000-011-7181': 1,
  'SL0000-011-7271': 1,
  'SL0000-011-7361': 1,
  'SL0000-011-7451': 1,
  'SL0000-011-7541': 1,
  'SL0000-011-7631': 1,
  'SL0000-011-7721': 1,
  'SL0000-011-7811': 1,
  'SL0000-011-7901': 1,
  'SL0000-011-7991': 1,
  'SL0000-011-8081': 1,
  'SL0000-011-8171': 1,
  'SL0000-011-8261': 1,
  'SL0000-011-8351': 1,
  'SL0000-011-8441': 1,
  'SL0000-011-8531': 1,
  'SL0000-011-8621': 1,
  'SL0000-011-8711': 1,
  'SL0000-011-8801': 1,
  'SL0000-011-8891': 1,
  'SL0000-011-8981': 1,
  'SL0000-011-9071': 1,
  'SL0000-011-9161': 1,
  'SL0000-011-9251': 1,
  'SL0000-011-9341': 1,
  'SL0000-011-9431': 1,
  'SL0000-011-9521': 1,
  'SL0000-011-9611': 1,
  'SL0000-011-9701': 1,
  'SL0000-011-9791': 1,
  'SL0000-011-9881': 1,
  'SL0000-011-9971': 1,
  'SL0000-012-0061': 1,
  'SL0000-012-0151': 1,
  'SL0000-012-0241': 1,
  'SL0000-012-0241-1': 1,
  'SL0000-012-0331': 1,
  'SL0000-012-0421': 1,
  'SL0000-012-0511': 1,
  'SL0000-012-0601': 1,
  'SL0000-012-0691': 1,
  'SL0000-012-0781': 1,
  'SL0000-012-0781-1': 1,
  'SL0000-012-0871': 1,
  'SL0000-012-0961': 1,
  'SL0000-012-1051': 1,
  'SL0000-012-1141': 1,
  'SL0000-012-1231': 1,
  'SL0000-012-1321': 1,
  'SL0000-012-1411': 1,
  'SL0000-012-1501': 1,
  'SL0000-012-1502': 1,
  'SL0000-012-1591': 1,
  'SL0000-012-1771': 1,
  'SL0000-012-1772': 1,

In [ ]:
id_field = "FACILITYID"

spatial_err_segs = [err["segment_id"] for err in errors if err.get("error_t") == "spatial"]

segs = lines_gdf.loc[lines_gdf[id_field].isin(spatial_err_segs)]

records = []
for _, line in segs.iterrows():

    endpoints = utils.extract_endpoints(line.geometry)
    
    for role, pt in zip(("from", "to"), endpoints):
        records.append({
            "segment_id": line[id_field],
            "role": role,
            "geometry": pt
        })
        
endpoints_gdf = gpd.GeoDataFrame(
    records,
    geometry="geometry",
    crs=segs.crs
)

endpoints_gdf["geom_buffer"] = endpoints_gdf.buffer(1)

seg_bufs = gpd.GeoDataFrame(
    endpoints_gdf[["segment_id", "role", "geom_buffer", "geometry"]],
    geometry="geom_buffer",
    crs=endpoints_gdf.crs
).rename(columns={"geometry":"endpoint"})

nearby_nodes = gpd.sjoin(nodes_gdf, seg_bufs, predicate="intersects", how="inner")

nearby_nodes["dist"] = nearby_nodes.geometry.distance(
    nearby_nodes["endpoint"]
)

nearby_nodes

,FACILITYID,TO_ASSET_ID,layer,geometry,index_right,segment_id,role,endpoint,dist
620,JP3572118478,None,ssFITTING,POINT Z (318493.927 4835944.012 0),17,SL1426097-1,to,POINT (318493.927 4835944.012),3.372603e-07
877,JP101361,SL110948,ssFITTING,POINT Z (302088.948 4833716.465 0),21,SL110923,to,POINT (302088.948 4833716.465),3.371031e-07
214413,MH5001912133,None,ssMANHOLE,POINT Z (312149.609 4850242.027 0),4,SL4030218,from,POINT (312149.609 4850242.027),3.357016e-07
243855,MH4729417331,None,ssMANHOLE,POINT Z (317346.732 4847516.616 0),23,SL4050884,to,POINT (317346.51 4847517.266),6.868650e-01
297530,MH2010420,None,ssMANHOLE,POINT Z (304915.635 4829264.625 0),12,SL110441,from,POINT (304915.635 4829264.625),3.368792e-07
297531,MH2010413,None,ssMANHOLE,POINT Z (304804.519 4829231 0),13,SL110441,to,POINT (304804.519 4829231),3.374857e-07
300740,MH2893004953,None,ssMANHOLE,POINT Z (304969.545 4829151.995 0),2,SL2008024,from,POINT (304969.545 4829151.995),3.360867e-07
311207,MH2010447,None,ssMANHOLE,POINT Z (304191.672 4841811.502 0),15,SL110440,to,POINT (304191.672 4841811.502),3.379179e-07
311210,MH2010455,None,ssMANHOLE,POINT Z (304220.987 4841714.053 0),10,SL110439,from,POINT (304220.987 4841714.053),3.365144e-07
311211,MH2010456,None,ssMANHOLE,POINT Z (304205.224 4841799.791 0),11,SL110439,to,POINT (304205.224 4841799.791),3.360642e-07
311211,MH2010456,None,ssMANHOLE,POINT Z (304205.224 4841799.791 0),14,SL110440,from,POINT (304205.224 4841799.791),3.360642e-07
314412,MH3004490,None,ssMANHOLE,POINT Z (310223.864 4849674.085 0),0,SL202006,from,POINT (310223.864 4849674.085),3.359522e-07
315821,MH3004511,None,ssMANHOLE,POINT Z (310253.538 4849683.477 0),1,SL202006,to,POINT (310253.538 4849683.477),3.358404e-07
316627,MH3241498248,None,ssMANHOLE,POINT Z (298264.734 4832636.572 0),8,SL2000980,from,POINT (298264.734 4832636.572),3.362214e-07
321101,MH3344202023A,None,ssMANHOLE,POINT Z (302054.792 4833669.434 0),19,SL110922,to,POINT (302054.792 4833669.434),3.380298e-07
321101,MH3344202023A,None,ssMANHOLE,POINT Z (302054.792 4833669.434 0),20,SL110923,from,POINT (302054.792 4833669.434),3.380298e-07
321854,MH3003254,None,ssMANHOLE,POINT Z (317346.51 4847517.266 0),23,SL4050884,to,POINT (317346.51 4847517.266),3.363114e-07
322637,MH2010967,None,ssMANHOLE,POINT Z (302025.529 4833627.248 0),18,SL110922,from,POINT (302025.529 4833627.248),3.363564e-07
323510,MH5512527861,None,ssMANHOLE,POINT Z (317398.129 4847530.434 0),22,SL4050884,from,POINT (317398.129 4847530.434),3.361315e-07
325387,MH4540901031A,None,ssMANHOLE,POINT Z (301168.616 4845543.275 0),7,SL4001667,to,POINT (301168.616 4845543.275),3.377616e-07
326013,MH5512527518,None,ssMANHOLE,POINT Z (312175.271 4850249.892 0),5,SL4030218,to,POINT (312175.271 4850249.892),3.349806e-07
326982,MH4540901031,None,ssMANHOLE,POINT Z (301051.322 4845625.605 0),6,SL4001667,from,POINT (301051.322 4845625.605),3.335781e-07
327113,MH2893004953A,None,ssMANHOLE,POINT Z (305015.414 4829156.472 0),3,SL2008024,to,POINT (305015.414 4829156.472),3.360418e-07
329321,MH3237498275,None,ssMANHOLE,POINT Z (298291.696 4832596.342 0),9,SL2000980,to,POINT (298291.696 4832596.342),3.364466e-07
333374,MH3010362,None,ssMANHOLE,POINT Z (318489.389 4835958.492 0),16,SL1426097-1,from,POINT (318489.389 4835958.492),3.360418e-07

In [27]:
dir_seg_lookup

{'SL9307': {'from': ['MH3848606859'], 'to': ['MH3847906855']},
 'SL9320': {'from': ['MH3847906855'], 'to': ['MH3839806880']},
 'SL1402455': {'from': ['MH4252412459'], 'to': ['CN8395']},
 'SL1402456': {'from': ['MH4253112486'], 'to': ['CN8396']},
 'SL24393': {'from': ['MH3803706077'], 'to': ['MH3802706070']},
 'SL53336': {'from': ['MH3847506018'], 'to': ['MH3848806064']},
 'SL53337': {'from': ['MH3848806064'], 'to': ['MH3848706071']},
 'SL53338': {'from': ['MH3848706071-1'], 'to': ['MH3849506096']},
 'SL50793': {'from': ['MH3759309686'], 'to': ['MH3756909693']},
 'SL50794': {'from': ['MH3756909693'], 'to': ['MH3752209709']},
 'SL9491': {'from': ['MH3845907082'], 'to': ['MH3837107110']},
 'SL9477': {'from': ['MH3805907172'], 'to': ['MH3803407092']},
 'SL9430': {'from': ['MH3801007013'], 'to': ['MH3791007043']},
 'SL9584': {'from': ['MH3806707199'], 'to': ['MH3799207223']},
 'SL21172': {'from': ['MH3725105628'], 'to': ['MH3722205637']},
 'SL7049': {'from': ['MH3772107502'], 'to': ['MH3778807484']},
 'SL7073': {'from': ['MH3766707515'], 'to': ['MH3771007503']},
 'SL23861': {'from': ['MH3537305803'], 'to': ['MH3539505817']},
 'SL23863': {'from': ['MH3539705817'], 'to': ['MH3542605912']},
 'SL23864': {'from': ['MH3537605802'], 'to': ['MH3536405763']},
 'SL52514': {'from': ['MH3561305223'], 'to': ['MH3555805224']},
 'SL52515': {'from': ['MH3555805224'], 'to': ['MH3555805191']},
 'SL52521': {'from': ['MH3556005214'], 'to': ['MH3556005192']},
 'SL22038': {'from': ['MH3692905199'], 'to': ['MH3698105183']},
 'SL23521': {'from': ['MH3725006790'], 'to': ['MH3731706726']},
 'SL23524': {'from': ['MH3720306472'], 'to': ['MH3722606538']},
 'SL23526': {'from': ['MH3721106544'], 'to': ['MH3722606538']},
 'SL23527': {'from': ['MH3710206582'], 'to': ['MH3721106544']},
 'SL23531': {'from': ['MH3725806649'], 'to': ['MH3734006578']},
 'SL23532': {'from': ['MH3721106692'], 'to': ['MH3725806649']},
 'SL7401': {'from': ['MH3785808068'], 'to': ['MH3793108046']},
 'SL7462': {'from': ['MH3780508198'], 'to': ['MH3789908170']},
 'SL1402457': {'from': ['MH4254712538'], 'to': ['CN8397']},
 'SL1402458': {'from': ['MH4255512564'], 'to': ['CN8398']},
 'SL1402460': {'from': ['MH4226912021'], 'to': ['MH4227712026']},
 'SL11705': {'from': ['MH3918806446'], 'to': ['MH3920106386']},
 'SL11732': {'from': ['MH3917506494'], 'to': ['MH3909406456']},
 'SL11726': {'from': ['MH3909406456'], 'to': ['MH3909006450']},
 'SL22037': {'from': ['MH3700105044'], 'to': ['MH3704704965']},
 'SL24929': {'from': ['MH3788505933'], 'to': ['MH3797305905']},
 'SL24936': {'from': ['MH3750305460'], 'to': ['MH3751705457']},
 'SL24939': {'from': ['MH3787805851'], 'to': ['MH3794905831']},
 'SL53525': {'from': ['MH3700405991', 'CN5730'], 'to': ['MH3711205959']},
 'SL21553': {'from': ['MH3726604492'], 'to': ['MH3725104436']},
 'SL23475': {'from': ['MH3732806189'], 'to': ['MH3733006180']},
 'SL22927': {'from': ['MH3716606363'], 'to': ['MH3708506392']},
 'SL22928': {'from': ['MH3708506392'], 'to': ['MH3703906408']},
 'SL22929': {'from': ['MH3703906408'], 'to': ['MH3702106406']},
 'SL22931': {'from': ['MH3706406494'], 'to': ['MH3703106417']},
 'SL53216': {'from': ['MH3851909406'], 'to': ['MH3850009339']},
 'SL11711': {'from': ['MH3909006450'], 'to': ['MH3910506393']},
 'SL11691': {'from': ['MH3910506393'], 'to': ['MH3910706346']},
 'SL1401114': {'from': ['MH4257412355'], 'to': ['MH4256812368']},
 'SL1401115': {'from': ['MH4255312279'], 'to': ['MH4257412355']},
 'SL1401117': {'from': ['MH4252912200'], 'to': ['MH4255312279']},
 'SL34284': {'from': ['MH3941610828'], 'to': ['MH3933710851']},
 'SL34084': {'from': ['MH3957410594'], 'to': ['MH3954210486']},
 'SL50101': {'from': ['MH3829011048'], 'to': ['MH3825711057']},
 'SL50478': {'from': ['MH3836410325'], 'to': ['MH3834310250']},
 'SL50482': {'from': ['MH3854110258'], 'to': ['MH3854210373']},
 'SL50483': {'from': ['MH3836710327'], 'to': ['MH3856010266']},
 'SL50142': {'from': ['MH3801511235'], 'to': ['MH3795311254']},
 'SL50145': {'from': ['MH3795611154'], 'to': ['MH3792911168']},
 'SL50146': {'from': ['MH3795711150'], 'to': ['MH3793011165']},
 'SL34022': {'from': ['MH3975910347'], 'to': ['MH3975010360']},
 'SL34033': {'from': ['MH3975010360'], 'to': ['MH3967310383']},
 'SL33966': {'from': ['MH3968610206'], 'to': ['MH3958310237']},
 'SL33977': {'from': ['MH3958310237'], 'to': ['MH3947710268']},
 'SL34013': {'from': ['MH3960510315'], 'to': ['MH3950010346']},
 'SL34044': {'from': ['MH3967310383'], 'to': ['MH3958810408']},
 'SL23415': {'from': ['MH3753506300'], 'to': ['MH3760006334']},
 'SL50861': {'from': ['MH3773409373'], 'to': ['MH3775409437']},
 'SL50862': {'from': ['MH3775609444'], 'to': ['MH3775409437']},
 'SL50863': {'from': ['MH3775609444'], 'to': ['MH3776009446']},
 'SL50867': {'from': ['MH3796409271'], 'to': ['MH3796909287']},
 'SL50868': {'from': ['MH3798009329'], 'to': ['MH3797209299']},
 'SL22419': {'from': ['MH3621305036'], 'to': ['MH3627905071']},
 'SL23134': {'from': ['MH3672306047'], 'to': ['MH3674506040']},
 'SL23135': {'from': ['MH3674206108'], 'to': ['MH3672306047']},
 'SL23139': {'from': ['MH3669406060'], 'to': ['MH3662106082']},
 'SL5406': {'from': ['MH3939907834'], 'to': ['MH3932707857']},
 'SL5395': {'from': ['MH3942307910'], 'to': ['MH3939907834']},
 'SL9517': {'from': ['JP103191'], 'to': ['CN16247']},
 'SL51497': {'from': ['MH3930208806'], 'to': ['MH3929308806']},
 'SL51499': {'from': ['MH3925608810'], 'to': ['MH3917208836']},
 'SL51500': {'from': ['MH3917208836', 'CN5745'], 'to': ['MH3909908857']},
 'SL51501': {'from': ['MH3909908857'], 'to': ['MH3904808872']},
 'SL51502': {'from': ['MH3904808872'], 'to': ['MH3895608899']},
 'SL4179338': {'from': ['MH5512528710'], 'to': ['MH3629803961']},
 'SL21119': {'from': ['MH3734905444'], 'to': ['MH3726205471']},
 'SL21120': {'from': ['MH3738905512'], 'to': ['MH3738405522']},
 'SL21121': {'from': ['MH3726205471'], 'to': ['MH3725405466']},
 'SL21150': {'from': ['MH3738205601'], 'to': ['MH3737605593']},
 'SL1400752': {'from': ['MH4303212573'], 'to': ['JP4296512595']},
 'SL1413166': {'from': ['CB4210612446'], 'to': ['MH4216512602']},
 'SL1400907': {'from': ['MH4299612451'], 'to': ['MH4301912532']},
 'SL1401014': {'from': ['MH4243412500'], 'to': ['MH4245812582']},
 'SL21151': {'from': ['MH3743705574'], 'to': ['MH3737605593']},
 'SL21158': {'from': ['MH3738405522'], 'to': ['MH3728105551']},
 'SL21159': {'from': ['MH3737605593'], 'to': ['MH3731305612']},
 'SL21161': {'from': ['MH3738205521'], 'to': ['MH3728105549']},
 'SL21162': {'from': ['MH3728105551'], 'to': ['MH3719505571']},
 'SL50907': {'from': ['MH3816809784'], 'to': ['MH3817109783']},
 'SL50908': {'from': ['MH3817109783'], 'to': ['MH3822209768']},
 'SL50909': {'from': ['MH3822209768'], 'to': ['MH3827609752']},
 'SL51068': {'from': ['MH3850209686', 'CN16118'], 'to': ['MH3842609708']},
 'SL51069': {'from': ['MH3842609708'], 'to': ['MH3842309698']},
 'SL51070': {'from': ['MH3842309698'], 'to': ['MH3841609700']},
 'SL23566': {'from': ['MH3732106508'], 'to': ['MH3702106406']},
 'SL22784': {'from': ['MH3654904546'], 'to': ['MH3660304512']},
 'SL1479900': {'from': ['MH3333114145'], 'to': ['MH3335614162']},
 'SL1401692': {'from': ['MH4243112675'], 'to': ['MH4235812686']},
 'SL1402453': {'from': ['MH4249812372'], 'to': ['CN8393']},
 'SL1402454': {'from': ['MH4250912401'], 'to': ['CN8394']},
 'SL22727': {'from': ['MH3684604666'], 'to': ['OF3689804619']},
 'SL25097': {'from': ['MH3605804994'], 'to': ['CN5728']},
 'SL25009': {'from': ['MH3805007722'], 'to': ['MH3798407715']},
 'SL25010': {'from': ['MH3798407715'], 'to': ['MH3796307716']},
 'SL7454': {'from': ['MH3863108266'], 'to': ['MH3861508157']},
 'SL7397': {'from': ['MH3804808010'], 'to': ['MH3795208039']},
 'SL7380': {'from': ['MH3807308095'], 'to': ['MH3804808010']},
 'SL7451': {'from': ['MH3807908114'], 'to': ['MH3798608142']},
 'SL7449': {'from': ['MH3808508110'], 'to': ['MH3798908138']},
 'SL7386': {'from': ['MH3803408007'], 'to': ['MH3798508022']},
 'SL5509': {'from': ['MH3877908012'], 'to': ['MH3870008036']},
 'SL9274': {'from': ['MH3867006918'], 'to': ['MH3864006823']},
 'SL9267': {'from': ['MH3864006823'], 'to': ['MH3863606812']},
 'SL9278': {'from': ['MH3863606812'], 'to': ['MH3858206829']},
 'SL9311': {'from': ['MH3858206829'], 'to': ['MH3848606859']},
 'SL1456476': {'from': ['MH3317006886'], 'to': ['MH3314406856']},
 'SL1456477': {'from': ['MH3314406856'], 'to': ['MH3311006817']},
 'SL1456478': {'from': ['MH3311006817'], 'to': ['MH3307406774']},
 'SL1456479': {'from': ['MH3307406774'], 'to': ['MH3305306749']},
 'SL1456550': {'from': ['MH3305306749'], 'to': ['MH3301906709']},
 'SL1454710': {'from': ['MH3318009673'], 'to': ['MH3317709687']},
 'SL1454711': {'from': ['MH3320009768'], 'to': ['MH3317709687']},
 'SL1453345': {'from': ['JP3366505860'], 'to': ['MH3363705844']},
 'SL1453346': {'from': ['JP3366505860'], 'to': ['MH3368305870']},
 'SL1456852': {'from': ['MH3355905887'], 'to': ['MH3354705946']},
 'SL2000-020-1262': {'from': ['MH4974433123-1'], 'to': ['MH4965133150']},
 'SL2000-020-1261': {'from': ['MH4974433123'], 'to': ['MH4965133150']},
 'SL1439045': {'from': ['MH3698510304'], 'to': ['MH3696810306']},
 'SL1438957': {'from': ['MH3695510214'], 'to': ['MH3694610162']},
 'SL1440580': {'from': ['MH3611111469'], 'to': ['MH3601011498']},
 'SL1435991': {'from': ['MH3766410526'], 'to': ['MH3763010536']},
 'SL1436884': {'from': ['MH3708710784'], 'to': ['MH3704710796']},
 'SL1436346': {'from': ['MH3704710796'], 'to': ['MH3701810804']},
 'SL1436348': {'from': ['MH3701710810'], 'to': ['MH3704210896']},
 'SL1436349': {'from': ['MH3704210896'], 'to': ['MH3706810981']},
 'SL1440688': {'from': ['MH3619910486'], 'to': ['MH3616810388']},
 'SL1441850': {'from': ['MH3600710187'], 'to': ['MH3598810124']},
 'SL1440135': {'from': ['MH3611310206'], 'to': ['MH3613610280']},
 'SL1457441': {'from': ['MH3297908520', 'CN6602'], 'to': ['MH3287508526']},
 'SL1457442': {'from': ['MH3290708518'], 'to': ['CN6602']},
 'SL1457546': {'from': ['MH3288208551'], 'to': ['MH3287508526']},
 'SL1457547': {'from': ['MH3286808544'], 'to': ['MH3288508545']},
 'SL1458796': {'from': ['MH3296808025'], 'to': ['MH3296007989']},
 'SL1458813': {'from': ['MH3298208196'], 'to': ['MH3296408143']},
 'SL1456860': {'from': ['MH3363906132'], 'to': ['MH3364606143']},
 'SL2000-023-3211': {'from': ['MH4428224072'], 'to': ['MH4435524049']},
 'SL2000-023-3301': {'from': ['MH4413624115'], 'to': ['MH4421024094']},
 'SL1456863': {'from': ['MH3365406021'], 'to': ['MH3362506105']},
 'SL1456864': {'from': ['MH3362506105'], 'to': ['MH3363306120']},
 'SL1441475': {'from': ['MH3648610603'], 'to': ['MH3646110523']},
 'SL1441476': {'from': ['MH3646110523'], 'to': ['MH3644310513']},
 'SL1438445': {'from': ['MH3644710782'], 'to': ['MH3646610844']},
 'SL1438549': {'from': ['MH3646610844'], 'to': ['MH3648410904']},
 'SL1438550': {'from': ['MH3648410904'], 'to': ['MH3648310928']},
 'SL1438659': {'from': ['MH3648310928'], 'to': ['MH3650711014']},
 'SL1439616': {'from': ['MH3646210835'], 'to': ['MH3648210903']},
 'SL1439617': {'from': ['MH3648210903'], 'to': ['MH3648110927']},
 'SL1440791': {'from': ['MH3692810736'], 'to': ['MH3690910664']},
 'SL1435140': {'from': ['MH3737510113'], 'to': ['MH3735410080']},
 'SL1435141': {'from': ['MH3735410080'], 'to': ['MH3734610056']},
 'SL1435142': {'from': ['MH3734610056'], 'to': ['MH3734010021']},
 'SL1436635': {'from': ['MH3713810498'], 'to': ['MH3706710520']},
 'SL1439302': {'from': ['MH3657310150'], 'to': ['MH3654610063']},
 'SL1439303': {'from': ['MH3681310035'], 'to': ['MH3672310062']},
 'SL1439372': {'from': ['MH3672310062'], 'to': ['MH3664810084']},
 'SL1439373': {'from': ['MH3664810084'], 'to': ['MH3666010124']},
 'SL1439778': {'from': ['MH3675510160'], 'to': ['MH3667310185']},
 'SL1438064': {'from': ['MH3667310185'], 'to': ['MH3659010207']},
 'SL1436262': {'from': ['MH3764310754'], 'to': ['MH3765310786']},
 'SL1435537': {'from': ['MH3765310786'], 'to': ['MH3766210812']},
 'SL1435538': {'from': ['MH3766210812'], 'to': ['MH3768410889']},
 'SL1435539': {'from': ['MH3768410889'], 'to': ['MH3770710970']},
 'SL1435540': {'from': ['MH3770710970'], 'to': ['MH3770610977']},
 'SL1435984': {'from': ['MH3785210965'], 'to': ['MH3781610976']},
 'SL1435553': {'from': ['MH3754510454'], 'to': ['MH3747010477']},
 'SL1435554': {'from': ['MH3747010477'], 'to': ['MH3738810501']},
 'SL1435289': {'from': ['MH3738810501'], 'to': ['MH3733210518']},
 'SL1435290': {'from': ['MH3733210518'], 'to': ['MH3727610535']},
 'SL1458739': {'from': ['MH3269207383'], 'to': ['MH3275607491']},
 'SL1458757': {'from': ['MH3269607515'], 'to': ['MH3267207528']},
 'SL1458763': {'from': ['MH3267207528'], 'to': ['MH3263007450']},
 'SL1457621': {'from': ['MH3279009841'], 'to': ['MH3276509842']},
 'SL1457689': {'from': ['MH3276509842'], 'to': ['MH3271609855']},
 'SL1457601': {'from': ['MH3271609855'], 'to': ['MH3269109868']},
 'SL1457602': {'from': ['MH3269109868'], 'to': ['MH3260609892']},
 'SL110577': {'from': ['MH2010604'], 'to': ['MH2010605']},
 'SL110578': {'from': ['MH2010605'], 'to': ['MH2010606']},
 'SL1457603': {'from': ['MH3260609892'], 'to': ['MH3252309915']},
 'SL1457604': {'from': ['MH3252309915'], 'to': ['CN6611']},
 'SL1448672': {'from': ['MH3404210361'], 'to': ['CN6821']},
 'SL1449222': {'from': ['MH3420310208'], 'to': ['CN6822']},
 'SL1451676': {'from': ['MH3411210287'], 'to': ['MH3404110306']},
 'SL1451677': {'from': ['MH3404110306'], 'to': ['MH3403310301']},
 'SL1448170': {'from': ['MH3403310301'], 'to': ['MH3403910238']},
 'SL1448171': {'from': ['MH3415110206'], 'to': ['MH3409510222']},
 'SL1448172': {'from': ['MH3409510222'], 'to': ['MH3403910238']},
 'SL1448173': {'from': ['MH3403910238'], 'to': ['MH3402110243']},
 'SL1458585': {'from': ['MH3267806995'], 'to': ['CN6589']},
 'SL1458605': {'from': ['MH3267706853'], 'to': ['MH3263406886']},
 'SL1450429': {'from': ['MH3421710036', 'CN6804', 'CN6803'],
  'to': ['MH3422409952']},
 'SL1451833': {'from': ['MH3421010124'], 'to': ['MH3421010120']},
 'SL1450950': {'from': ['MH3422409963'], 'to': ['CN6803']},
 'SL1450951': {'from': ['MH3422209988'], 'to': ['CN6804']},
 'SL1451709': {'from': ['MH3423410291'], 'to': ['MH3423610302']},
 'SL1451300-1': {'from': ['MH3423610302A'], 'to': ['MH3433110275']},
 'SL1451301': {'from': ['MH3423610302'], 'to': ['MH3421210308']},
 'SL1451302': {'from': ['MH3421210308'], 'to': ['CN6805']},
 'SL1446499': {'from': ['MH3547211966'], 'to': ['MH3538811991']},
 'SL1443760': {'from': ['MH3538811991'], 'to': ['MH3529412018']},
 'SL1438581': {'from': ['MH3673811486'], 'to': ['MH3673411502']},
 'SL1438582': {'from': ['MH3677511353'], 'to': ['MH3678611391']},
 'SL1450882': {'from': ['MH3466511538'], 'to': ['MH3473911517']},
 'SL1450883': {'from': ['MH3456011568'], 'to': ['MH3466511538']},
 'SL1450884': {'from': ['MH3456011568'], 'to': ['MH3447411593']},
 'SL1444558': {'from': ['MH3529010865'], 'to': ['MH3521110888']},
 'SL1444559': {'from': ['MH3521110888'], 'to': ['MH3513310909']},
 'SL1444560': {'from': ['MH3513310909'], 'to': ['MH3505910930']},
 'SL1444561': {'from': ['MH3505910930'], 'to': ['MH3499110949']},
 'SL1444267': {'from': ['MH3506810649'], 'to': ['MH3513810629']},
 'SL1444613': {'from': ['MH3594810667'], 'to': ['MH3585510695']},
 'SL1443374': {'from': ['MH3568810742', 'CN6752'], 'to': ['MH3557410777']},
 'SL1443305': {'from': ['MH3578710712'], 'to': ['MH3568810742']},
 'SL1440387': {'from': ['MH3650011149A'], 'to': ['MH3645611161']},
 'SL4000-020-1101': {'from': ['MH4959333009-1'], 'to': ['MH4961833086-1']},
 'SL208790': {'from': ['MH4869318412A'], 'to': ['MH3011195']},
 'SL1440643': {'from': ['MH3645611161'], 'to': ['MH3644611164']},
 'SL1439759': {'from': ['MH3677911646'], 'to': ['MH3673211660']},
 'SL1439760': {'from': ['MH3673211660'], 'to': ['MH3670211560']},
 'SL1439761': {'from': ['MH3651411724'], 'to': ['MH3647611736']},
 'SL1438583': {'from': ['MH3678611391'], 'to': ['MH3680811469']},
 'SL1442161': {'from': ['MH3650411342'], 'to': ['MH3649811358']},
 'SL1438588': {'from': ['MH3605111799'], 'to': ['MH3593411832']},
 'SL1438589': {'from': ['MH3646311893'], 'to': ['MH3636711920']},
 'SL1438590': {'from': ['MH3636711920'], 'to': ['MH3627511946']},
 'SL1438591': {'from': ['MH3627511946'], 'to': ['MH3618311973']},
 'SL110442': {'from': ['MH4246809604'], 'to': ['MH2010457']},
 'SL208791': {'from': ['MH3011200'], 'to': ['MH3011195']},
 'SL1438953': {'from': ['MH3626511203'], 'to': ['CN6689']},
 'SL1440599': {'from': ['MH3640111491'], 'to': ['MH3637611407']},
 'SL1440034': {'from': ['MH3605811198', 'CN6684'], 'to': ['MH3607811257']},
 'SL1441293': {'from': ['MH3621911332'], 'to': ['CN6690']},
 'SL1441294': {'from': ['MH3615711348'], 'to': ['CN6691']},
 'SL1441295': {'from': ['MH3611111361'], 'to': ['CN6692']},
 'SL1441137': {'from': ['MH3607810794'], 'to': ['MH3603810806']},
 'SL1441246': {'from': ['MH3607210643'], 'to': ['MH3610010732']},
 'SL5000-020-1112': {'from': ['MH5000333044-1'], 'to': ['MH4986633087-1']},
 'SL5000-020-1111': {'from': ['MH5000333044'], 'to': ['MH4986633087']},
 'SL208792': {'from': ['MH3011201'], 'to': ['MH3011200']},
 'SL110594': {'from': ['MH2010629'], 'to': ['MH2010628']},
 'SL1441247': {'from': ['MH3610010732'], 'to': ['MH3612610819']},
 'SL1441253': {'from': ['MH3611610655'], 'to': ['MH3614310741']},
 'SL1439932': {'from': ['MH3614310741'], 'to': ['MH3616510809']},
 'SL1440619': {'from': ['JP3622110581'], 'to': ['MH3621110584']},
 'SL1440620': {'from': ['MH3621110584'], 'to': ['MH3616510598']},
 'SL1440623': {'from': ['MH3609310620'], 'to': ['MH3602210641']},
 'SL1436678': {'from': ['MH3775810784'], 'to': ['MH3774410773']},
 'SL1436679': {'from': ['MH3775110760'], 'to': ['MH3774410773']},
 'SL1436680': {'from': ['MH3774310735'], 'to': ['MH3775110760']},
 'SL1436681': {'from': ['MH3772510671'], 'to': ['MH3774310735']},
 'SL1436682': {'from': ['MH3772510671', 'CN6639'], 'to': ['MH3769410563']},
 'SL1440932': {'from': ['MH3619210063'], 'to': ['MH3609510091']},
 'SL1440933': {'from': ['MH3609510091'], 'to': ['MH3608810093']},
 'SL1438571': {'from': ['MH3692610987'], 'to': ['MH3693311015']},
 'SL1471595': {'from': ['MH3680014678'], 'to': ['CN7318']},
 'SL1471049': {'from': ['MH3681813576', 'CN7321', 'CN7322'],
  'to': ['MH3669213614']},
 'SL1469804': {'from': ['MH3628714738', 'CN7356'], 'to': ['MH3631214823']},
 'SL1472480': {'from': ['MH3505412091'], 'to': ['MH3495012122']},
 'SL1473448': {'from': ['MH3583712551'], 'to': ['MH3585312607']},
 'SL203620': {'from': ['MH3006112'], 'to': ['MH3006076']},
 'SL203621': {'from': ['MH3006141'], 'to': ['MH3006139']},
 'SL203622': {'from': ['MH3006140'], 'to': ['MH3006138']},
 'SL203623': {'from': ['MH3006138'], 'to': ['MH3006137']},
 'SL203624': {'from': ['MH3006139'], 'to': ['MH3006136']},
 'SL203508': {'from': ['MH3006004'], 'to': ['MH3006002']},
 'SL203509': {'from': ['MH3006003'], 'to': ['MH3005976']},
 'SL203510': {'from': ['MH3006002'], 'to': ['MH3005977']},
 'SL203517': {'from': ['JP103349'], 'to': ['MH3006008']},
 'SL110579': {'from': ['MH2010606'], 'to': ['MH2010607']},
 'SL110580': {'from': ['MH2010607'], 'to': ['MH2010608']},
 'SL203518': {'from': ['JP103350'], 'to': ['MH3006009']},
 'SL1475188': {'from': ['MH3557514594', 'CN5952'], 'to': ['MH3559214650']},
 'SL1467613': {'from': ['MH3715913066', 'CN7178'], 'to': ['MH3720213052']},
 'SL1466936': {'from': ['CB3786114151', 'CN7247'], 'to': ['MH3782814182']},
 'SL1466979': {'from': ['MH3764614249'], 'to': ['MH3755514447']},
 'SL1470773': {'from': ['MH3607312890', 'CN7267'], 'to': ['MH3598412916']},
 'SL1469908': {'from': ['MH3696613102', 'CN7300'], 'to': ['MH3694013005']},
 'SL1412672': {'from': ['MH3955712322'], 'to': ['MH3955112365']},
 'SL1412673': {'from': ['MH3955112365'], 'to': ['JP3955112365A']},
 'SL1405684': {'from': ['MH4068412548', 'CN8507'], 'to': ['MH4059412574']},
 'SL1407982': {'from': ['MH4067212503', 'CN8500'], 'to': ['MH4047612542']},
 'SL1407999': {'from': ['MH4037612730', 'CN8529', 'CN8528'],
  'to': ['MH4019412826']},
 'SL1407316': {'from': ['MH4075213851'], 'to': ['MH4053413919']},

In [30]:
def not_already_connected(row):
    seg = row["segment_id"]
    role = row["role"]
    node = row["FACILITYID"]  # or whatever field
    
    return node not in dir_seg_lookup[seg][role]

nearby_nodes = nearby_nodes[
    nearby_nodes.apply(not_already_connected, axis=1)
]

idx = (
    nearby_nodes
    .groupby(["segment_id", "role"])["dist"]
    .idxmin()
)

best_candidates = nearby_nodes.loc[idx]

best_candidates

,FACILITYID,TO_ASSET_ID,layer,geometry,index_right,segment_id,role,endpoint,dist
311211,MH2010456,None,ssMANHOLE,POINT Z (304205.224 4841799.791 0),11,SL110439,to,POINT (304205.224 4841799.791),3.360642e-07
311211,MH2010456,None,ssMANHOLE,POINT Z (304205.224 4841799.791 0),14,SL110440,from,POINT (304205.224 4841799.791),3.360642e-07
311211,MH2010456,None,ssMANHOLE,POINT Z (304205.224 4841799.791 0),11,SL110439,to,POINT (304205.224 4841799.791),3.360642e-07
311211,MH2010456,None,ssMANHOLE,POINT Z (304205.224 4841799.791 0),14,SL110440,from,POINT (304205.224 4841799.791),3.360642e-07
321101,MH3344202023A,None,ssMANHOLE,POINT Z (302054.792 4833669.434 0),19,SL110922,to,POINT (302054.792 4833669.434),3.380298e-07
321101,MH3344202023A,None,ssMANHOLE,POINT Z (302054.792 4833669.434 0),20,SL110923,from,POINT (302054.792 4833669.434),3.380298e-07
321101,MH3344202023A,None,ssMANHOLE,POINT Z (302054.792 4833669.434 0),19,SL110922,to,POINT (302054.792 4833669.434),3.380298e-07
321101,MH3344202023A,None,ssMANHOLE,POINT Z (302054.792 4833669.434 0),20,SL110923,from,POINT (302054.792 4833669.434),3.380298e-07
333374,MH3010362,None,ssMANHOLE,POINT Z (318489.389 4835958.492 0),16,SL1426097-1,from,POINT (318489.389 4835958.492),3.360418e-07
243855,MH4729417331,None,ssMANHOLE,POINT Z (317346.732 4847516.616 0),23,SL4050884,to,POINT (317346.51 4847517.266),6.868650e-01